### ISSUE TITLE
Admin Console Languages

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1286]
### Summary of the new feature / enhancement

It would be great to offer translations for the admin console.

**Comment by DataTraveler1** [comment]
@adamdriscoll - The [Microsoft Terminology Portal](https://www.microsoft.com/en-us/language/Search) (with API) could be helpful in addition to volunteers. The portal shows how Microsoft chose to translate a particular word or expression and for which product (since the translation can vary sometimes)

![image](https://user-images.githubusercontent.com/537287/175504445-1be2dc34-2483-4069-9fd3-302274c52661.png)
###### figure shows "Scheduled Jobs" translated to German

I assume the first step is to have a localization in en-us and then build out from there?

**Comment by adamdriscoll** [comment]
Yep. We need to get the localization system in place and generate all the en-us strings and then we can translate from there.

**Comment by rwidmark** [comment]
I can translate to Swedish just send me a email with info.
robin@stolpe.io

**Comment by adamdriscoll** [comment]
@mattselle - This is kind of a big one but you could kinda do it a page at a time. The framework is in place. We just need to go through and replace a bunch of strings.

**Comment by adamdriscoll** [comment]
We should research this for the new admin console #2975

**Comment by adamdriscoll** [comment]
The general functionality is implemented. Let's open issues for each language.
