### ISSUE TITLE
Allow comments in endpoints.ps1 and scripts.ps1

### ISSUE THREAD

**Issue by mikedhanson** [ironmansoftware/powershell-universal#1401]
### Summary of the new feature / enhancement

Currently when you edit the files from the PSU UI it will auto format and save over any comments in the files. However you can add comments and such to the file itself and everything functions as it should. 

I think it would also be nice to utilize splats in the scripts.ps1.

![image](https://user-images.githubusercontent.com/15201245/180218781-f3e38bd1-65d1-4c8e-8cd1-edd5ecbd5362.png)

**Comment by alexrgreenwood** [comment]
not tried it myself but this might be what you are after on the splatting (v3)

![image](https://user-images.githubusercontent.com/23561607/180244439-b013ec1e-9486-4e3c-95e4-37f5776f322c.png)

**Comment by mikedhanson** [comment]
Interesting I didn't know this existed. The majority of our instances are not on version 3 yet but its something we will definitely use.

However even if you use this and add comments outside the splat and make a change via the UI it removes it. Not sure this will ever change due to the design of the platform but figured id mention it anyways.

**Comment by adamdriscoll** [comment]
Due to how the PowerShell parser and AST work, it's really hard to maintain comments in auto-generated scripts like PSU. That said, we are adding header and footer regions in version 3.7. The idea is that you can put whatever within the regions and PSU won't touch that area. Resources (e.g. endpoints\scripts\dashboards) generated in these regions will be read only in the admin console. 

This means you can programmatically generate resources and also edit the file in the admin console without things getting messed up. 

```powershell
#region PSUHeader

# We won't touch this

Get-Content .\endpoints.json  | ConvertFrom-Json | ForEach-Object {
# These are readonly
   New-PSUEndpoint -Url $_.Url -Endpoint {}
}

#endregion

# This is not readonly and can be edited in the admin console. 
   New-PSUEndpoint -Url '/' -Endpoint {}
```
