### ISSUE TITLE
Managed Data Storage

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1407]
### Summary of the new feature / enhancement

The idea with this is that users could hook scheduled scripts up to a managed data storage mechanism. There would be a new Data pane under Platform where you could select a schedule to store the data. It's mostly just an easier way to store job data. 

When data storage is configured you could store it in either the database or within memory. You could then reference the data in APIs, jobs, dashboards and pages. 

Data would have the following properties: 

- Persistence type (memory,database)
- Length - Forever, absolute expiration, sliding expiration
- Length settings (absolute expiration datetime or timespan of sliding expiration) 

You should be able to view and clear data from the admin console .

Data would be accessible in in PowerShell by using the `$Data:` scope. If you had a data provider setup that was called Groups, it would be available as `$Data:Groups` in your scripts. 

A use-case for this would be loading a set of AD groups and storing them in managed data storage.  You could then use those groups in authentication, APIs and dashboards without having to hit AD again. Every 20 minutes, a scheduled script would hit AD and reload the data in the Groups managed data record.

**Comment by donlent** [comment]
Hi Adam
This is a really good idea! 
One question though: Do you envision to also allow the creation of managed custom tables as well?
If yes, this could mean that we can create a "store" for managed data like logs wihch are directly stored in the sql db of PSU instead of creating a separate DB with dedicated tables.

**Comment by adamdriscoll** [comment]
@donlent - I'm not sure about the dedicated tables yet. It would make data indexing and retrieval much faster and more managed.

**Comment by adamdriscoll** [comment]
Some additional ideas after a chat with another user. 

- Support for triggers when objects are updated, created, deleted
- Configurable schema that allow for data types and attributes like readonly, required, validation etc
- Data history for auditing 
- Granular RBAC

**Comment by mabster** [comment]
Just on this one: The existing $Cache scope (and Set/Get-PSUCache) is an in-memory cache, right? It won't survive a restart of the app service?

I'm looking at using the Graph "user delta" function to pull a list of users who have been modified since we last checked, and to do that I'll need to store the delta token somewhere. The initial query to generate that delta token will pull down all ~200k users from our directory so I want to make sure that token persists. :)

**Comment by adamdriscoll** [comment]
We've integrated this with Set-PSUCache. You can use the -Persist to store to the database. It effectively is a distributed cache (#1198). We've implemented it pretty simply by introducing a single DataItem table that contains the CliXml for the objects that are stored. We haven't implemented the other features yet as we'll see how much this is actually used and what users actually end up needing from it.
