### ISSUE TITLE
PowerShell Universal does not work with PowerShell 7.1

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1464]
### Steps to Reproduce

Error message is: Could not load file or assembly 'System.ServiceModel.Primitives'

Workaround: Upgrade to PowerShell 7.2

### Expected behavior

```console
Works with PowerShell 7.1
```

### Actual behavior

```console
Doesn't load assemblies
```

### Environment data

3.2

**Comment by DataTraveler1** [comment]
@adamdriscoll - Could you please advise on PSU support for 7.0 LTS & 7.3 (preview)?

**Comment by adamdriscoll** [comment]
@DataTraveler1 - I have a hunch that 7.0 will not work but 7.3 will. I can validate when I have some time.

**Comment by DataTraveler1** [comment]
@adamdriscoll - As predicted, the current PowerShell 7.0 LTS does not work. The dashboard will be stuck in 'Started' mode. PowerShell 7.3 preview does work (pictured).

![image](https://user-images.githubusercontent.com/537287/184546429-a320ea41-db93-4ce7-ac95-f6d5403fa6e4.png)

**Comment by DataTraveler1** [comment]
@adamdriscoll - I forgot to mention that PowerShell 7.3 preview will not be recognized by PSU out of the box. I believe this is because the path that gets added to the PATH does not include **pwsh.exe**. Rather, the PATH statement points to a 'preview' sub-directory within the usual expected directory. The sub-directory contains a .cmd file.

![image](https://user-images.githubusercontent.com/537287/184549077-f263edce-f492-4e64-9a2e-0e92b297999a.png)

After modifying my PATH to remove the ``\preview`` sub-directory, the **pwsh.exe** from the PowerShell Preview was detected by PSU as an available environment.

Would this be a feature request for PSU to check for **pwsh-preview.cmd** along the PATH and then use the **pwsh.exe** from that paths parent directory? That could make it any easier for anyone who wants to use Preview with PSU.

**Comment by adamdriscoll** [comment]
@DataTraveler1 - Thanks for testing all this out! We should discover preview versions as well. Let's open a feature request for that.

**Comment by DataTraveler1** [comment]
@adamdriscoll #1484 has been raised 👍
