### ISSUE TITLE
Custom Login Logic

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1469]
### Summary of the new feature / enhancement

The use case is to have a custom login script rather than just forms login. It should also be possible to have multiple login types and select from a drop down. 

https://forums.ironmansoftware.com/t/custom-login-page/2039/9

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/custom-login-page/2039/10

**Comment by augiaugi** [comment]
@adamdriscoll is there any ETA for this feature? It would be pleasure to help you out with feature requirements etc.

**Comment by adamdriscoll** [comment]
@adamdriscoll - I'll likely want to pass some ideas past you to make sure I understand this best and it meets your needs.

**Comment by augiaugi** [comment]
I was thinking about a customizable login form (by using PU components and logic) that will eighter replace or pass custom data to the `authentication.ps1`

[https://docs.powershelluniversal.com/config/security?example-forms-authentication-with-active-directory#forms-authentication](url)

Be aware that it might be safe to have a fallback authentication logic (like the current one?), because while developing you can lockout yourself easily.
