### ISSUE TITLE
Two Tables in UDDynamics Can Cause a Failure to Render a table

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1561]
### Steps to Reproduce

The $EventData variable in one of the tables can end up $null and prevent the table from rendering rows properly. 

### Expected behavior

```console
$EventData is always populated
```

### Actual behavior

```console
$EventData is $null sometimes
```

### Environment data

3.3.1

**Comment by donlent** [comment]
Dear @adamdriscoll 
Have you ever found anything about this issue?
Unfortunately on my side it seems really weird and somehow also related to the use of Tables with  -LoadData I think since I haven't seen this issue before with "simple" tables...

I keep getting:
"Cannot bind argument to parameter 'InputObject' because it is null. "

and also (on DB queries):
"An error occurred: Cannot validate argument on parameter 'Query'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again."

What I've noticed is that I can somehow "drain" the issue by avoiding to autorefresh the tables I have in a dashboard at the same interval... But If I try to refresh the tables at the same time it gets only worse and this error keeps happening...

Do you want me to open a support ticket to analyze this issue on our environment?

Environment using right now:
3.4.4

Thanks a lot,
Don

**Comment by adamdriscoll** [comment]
I can reproduce this issue and it simply was not prioritized correctly. I've moved it into our current milestone.

**Comment by donlent** [comment]
Ah thanks a lot @adamdriscoll!
I'm so happy that you were able to identify this issue since it is really annoying and makes everything look as it was buggy... :-/
Kind regards,
Don
