### ISSUE TITLE
Custom title in browser tab/window title

### ISSUE THREAD

**Issue by mojoaar** [ironmansoftware/powershell-universal#1645]
### Summary of the new feature / enhancement

Today we can set the instance name with the setting: "Admin Console Title". It would be great if we could do the same the browser tab/window title (html tag: title).

When you have multiple tabs opened in a load balanced setup, it is easy to select the wrong instance/node as the title is "PowerShell Universal" on all tabs.
![psu_title](https://user-images.githubusercontent.com/21560785/197996810-ef3ddd82-9372-4920-9fda-8c59a12493c5.png)

### Proposed technical implementation details (optional)

Allow us to set the html tag title in the admin interface.

**Comment by schubfre** [comment]
I would like to add to this. Currently it is not possible to use variables in the Admin Console Title. If one has two environments for example - Dev and Prod - and a variable $PSUEnv and this variable is used in the title it will simply show "$PSUEnv" instead of "Dev" or "Prod".

![image](https://user-images.githubusercontent.com/28289080/198064614-d9f171e6-f54a-42c9-a36a-38ece526263a.png)

![image](https://user-images.githubusercontent.com/28289080/198064476-8e781cd5-310e-4e2e-a160-1d66332c977d.png)

**Comment by adamdriscoll** [comment]
@schubfre If you edit the settings.ps1 manually, you can get this to work. 

```
$Parameters = @{
	LoggingFilePath = "C:\ProgramData/PowerShellUniversal/log.txt"
	LogLevel = "Error"
	MicrosoftLogLevel = "Debug"
	AdminConsoleTitle = "$Platform"
}
Set-PSUSetting @Parameters
```

<img width="727" alt="image" src="https://user-images.githubusercontent.com/1256531/198376086-4419c5fd-1112-4582-82ea-9d9109ab0871.png">


<img width="121" alt="image" src="https://user-images.githubusercontent.com/1256531/198376115-22d26642-d44e-4d58-b9a9-92d75e83eaf7.png">
