### ISSUE TITLE
Persistent regions in PS configuration files. 

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1725]
### Summary of the new feature / enhancement

Currently, PS Configuration files are overwritten each time something changes. We should introduce a way to define a region that users can add custom code to those config files. 

```powershell
#region PSUDontTouchThis

## The folder where PSFeed scripts will be downloaded to. This must be set to ignore ps1 files git/ignore
$feedFolder = "$pwd\scripts\psfeed"

# Ensure that directory exists
New-Item -Path $feedFolder -ItemType Directory -ErrorAction SilentlyContinue | Out-Null

# List of scripts to pull from the PSFeed that are used in this PSUN instance.
$feedScripts = @(
    'Set-SFAADUserPhoto' # Used for the photo update portal page
    'Get-SFUserActiveADUsers' # Used to get a list of active users
)

# Loop and add every script from the PSFeed array
$feedScripts | foreach {
    Save-PSResource -Name $_ -Path $feedFolder -TrustRepository
    $psuHash =     @{
        Name        = "$_.ps1"
        Path        = "psfeed\$_.ps1"
        Environment = 'Windows PowerShell 5.1'
        ErrorAction = 'Stop'
    }
    New-PSUScript @psuHash
}

# Any scripts that are manually added, that need to be wrapped before execution in some way
$scripts = @(
    @{
        Name        = 'New-PreJoiners.ps1'
        Path        = 'New-PreJoiners.ps1'
        Environment = 'Windows PowerShell 5.1'
        ErrorAction = 'Stop'
```

**Comment by schubfre** [comment]
Would it be possible to solve my use-case #1504 with this? So instead of putting the files in the .gitignore and not having them tracked at all, I remove them from the .gitignore and write the environment specific variables and roles in this 'region'? 

Would that also be possible with the license?
Now that I come to think of it, how do others solve this problem currently? Surely I'm not the only one with a dev and prod env, where dev is push&pull and prod is pull only. So at least you need two different licenses and can't have the file on prod be populated by a git pull

**Comment by adamdriscoll** [comment]
This would likely solve that issue as well. You could have something like: 

```
#region PSUHeader
# This is a readonly region. 
if ($Env:Environment -eq 'PROD) {
  Set-PSULicense -Key '123' 
} else {
   Set-PSULicense -Key '456' 
}

#endregion 
```
