### ISSUE TITLE
Set container hostname via environment variable

### ISSUE THREAD

**Issue by MattHarrisUltima** [ironmansoftware/powershell-universal#1776]
### Summary of the new feature / enhancement

I would like to be able to set a container hostname via an environment variable.

Currently, when I deploy a PowerShell Universal image while using Azure Container Instances the hostname sets as 'sandboxhost638055734008819914' with a different number each time. I would like to be able to reference each container we deploy specifically.

A list of published environment variables for any included stacks (Ubuntu, ASP.NET, etc) would be nice to have if these lists exist.

**Comment by adamdriscoll** [comment]
PSU bases the hostname off of the current /etc/hostname for the machine. Using docker cli, you can use --hostname to set it manually. I'm not sure how to do this is an azure app service. 

It is possible to set it with docker compose but that is only preview in azure app services. 

https://stackoverflow.com/questions/29924843/how-do-i-set-hostname-in-docker-compose

I do think this is a valid issue but there may be a workaround you could figure out since docker does support setting hostnames.

**Comment by MattHarrisUltima** [comment]
Hi Adam,

Thank you for the prompt reply.

Docker Compose and WebApp's are out of scope there. The Image has been pulled directly from the ironmansoftware/universal repository on Docker Hub. while browsing the image layers I am unable to find any 'hostname' command parameter inside the published Dockerfile image layers.

I am hoping to trace where the hostname 'sandboxXXXXXXXXX' is generated, in order to rename the container when it is deployed.

**Comment by adamdriscoll** [comment]
We've added a new appsettings value that you can use to change the node name.

**Comment by MattHarrisUltima** [comment]
Thank you, Adam.

I look forward to trying this out.
