### ISSUE TITLE
Pro Tools for JetBrains Rider?

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1966]
I have gotten in love with JetBrains Rider for C#, and it has a powershell extension as well.
It would be nice if Pro Tools was released for JetBrain Rider for mac arm64.

P.S Pro Tools for vscode macOS still won't work :(

**Comment by adamdriscoll** [comment]
I find it unlikely we will implement this any time soon. It's mostly due to priorities and demand. 

As for VS Code for Mac OS: Have you tried to authorize the application in the Apple security settings? 

https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

I had to do this with PowerShell Universal on my M1. That said, I did not have to do this with the VSCode extension on my M1.

**Comment by rwidmark** [comment]
> I find it unlikely we will implement this any time soon. It's mostly due to priorities and demand. 
> 
> 
> 
> As for VS Code for Mac OS: Have you tried to authorize the application in the Apple security settings? 
> 
> 
> 
> https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac
> 
> 
> 
> I had to do this with PowerShell Universal on my M1. That said, I did not have to do this with the VSCode extension on my M1. 

I'll try that later.

**Comment by rwidmark** [comment]
> I find it unlikely we will implement this any time soon. It's mostly due to priorities and demand.
> 
> As for VS Code for Mac OS: Have you tried to authorize the application in the Apple security settings?
> 
> https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac
> 
> I had to do this with PowerShell Universal on my M1. That said, I did not have to do this with the VSCode extension on my M1.

@adamdriscoll  what application should I allow? I have re-installed my MacBook Pro and same issue. The issue are the same at my brand new Mac Studio also.

**Comment by adamdriscoll** [comment]
It should be the file in here: /Users/xxxx/PowerShellProTools/2022.11.2/osx-arm64/PowerShellProTools.Host
