### ISSUE TITLE
User based Git commit

### ISSUE THREAD

**Issue by Daniel0023** [ironmansoftware/powershell-universal#1974]
### Summary of the new feature / enhancement

When commit to Git, it would be nice only to commit your own changes and not changes made by other users. This would also be useful to prevent merge conflicts.

### Proposed technical implementation details (optional)

Let the sync engine track what changes a user has made and only be able to commit those, instead of all changes.

**Comment by Omzig** [comment]
interesting... the best way to deal with this right now is by having a local copy on your machine in a different branch, then do a PR.

**Comment by timosemmler** [comment]
I do not believe that this is so easily possible, but I also find the idea very important.

Why?
The changes are written directly into ONE local repository, if several users make changes at the same time, they are of course all written into this repository.

Basically, I find the idea very interesting, because we will soon be facing this challenge too. But so far I can only imagine that this is only possible if we make new changes together via GitLab and then distribute them to our servers.

In order for your wish to come true, the entire logic would probably have to be rewritten, e.g. each user would have to be able to specify their own local folder path for their own repository (and then there is still the logic missing to transfer all changes back centrally to the server instance for everyone).

Or you use the suggestion of @Omzig and new local branches are automatically created for each user account when they start the edit mode to transfer all changes there. Then the changes would only become active later via merges in the 'main' branch. But here, too, some changes in the web interface would be required in order to be able to manage these different states centrally. Perhaps users need a "higher" role to be able to resolve conflicts of users with a "lower" role?

Edit:
Forget the last paragraph, I just noticed when reading through it again that with this approach we would still be working in the same repository locally and that several branches cannot be active at the same time...

**Comment by Daniel0023** [comment]
We use PSU in the HA setup with shared Git repo, external SQL DB and with multiple users, which from time to time triggers a lot of merge conflits. Which are pain to sort out some times… 

Using the external SQL in HA setup brings a lot of value and saved time in configuration etc. but still have some issues…

The issue for us is that we use a shared external SQL DB between the nodes. The Git config is located in the DB, which means only one config and branch can be used for the whole setup. 

There by we are not able to do local branches, as PSU automatically will clone the repo from the branch defined in the SQL DB.
