### ISSUE TITLE
New-UDLineBreak and more

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#1997]
### Summary of the new feature / enhancement

As a developer, I want a cmdlet to line break for me so that i can quickly put a nice form together with good spacing. 

### Proposed technical implementation details (optional)
Maybe we can create a module with all the extra goodies like this and others?
```powershell
function New-UDLineBreak{
    New-UDElement -Tag div -Content{
        New-UDElement -Tag br
    }
}
```
### UniversalExtras or UniversalHelpers or UniversalToolbox or UniversalCommands or UniversalFormatting or UniversalUtility
- [ConvertTo-UDJson](https://blog.ironmansoftware.com/convertto-json-memory/)
- [New-UDCenter](https://blog.ironmansoftware.com/universal-dashboard-center-content#new-udcenter-function)
- New-UDLineBreak
- etc

**Comment by adamdriscoll** [comment]
I added LineBreak to this module: https://github.com/ironmansoftware/dashboard-utils

It's published as a template and can be directly added to PSU. Feel free to either add or open issues for the other items! Otherwise, I'll add them when I get time. 

I'd also be publishing this to the PSGallery but haven't yet, though, I might rename it.
