### ISSUE TITLE
PowerShell Packager - Unknown license status

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#2015]
## Symptom
Executables created through PowerShell Packager 2023.1.0 throw an exception for "unknown license status"

## Workaround
Downgrade to a lower version [PowerShell Packager 2022.12.2](https://imsreleases.blob.core.windows.net/packager/PowerShellPackager.2022.12.2.exe) (3.69MB)

## To Reproduce
Create an executable using PowerShell Packager 2023.1.0

## Expected behavior
I expected there not to be an exception thrown and for the script to execute as it does in the previous version 2022.12.2

## Screenshots
![image](https://user-images.githubusercontent.com/537287/215258032-ecede63f-2ae8-46f0-bcde-4233780d42b7.png)

## Version
This bug applies only to version 2023.1.0

## Acknowledgements
Thanks very much to the person who reported this on the Ironman Software Discord 👍

Edit 1 - Forgot to add workaround

**Comment by adamdriscoll** [comment]
@DataTraveler1 - I can't reproduce this one. Are there any particular settings you are enabling?

**Comment by adamdriscoll** [comment]
@DataTraveler1 - Could you send me an exe that has this problem?

**Comment by jerko-lenex** [comment]
I'm not sure if the issue I'm having is the same, but the symptoms are the same.
Rather than using PoSh Packager directly, I use VSCodium and PoSh Pro Tools v2023.1.0 to package my executable and I was able to reproduce this with the following details.

Specifying a `ApplicationIconPath` seems to cause the error, in my case at least.

```PowerShell
# test.ps1

$Test = "Test"
$Test
```

```PowerShell
# package.psd1

@{
    Root = '...\test.ps1'
    OutputPath = '...\out'
    Package = @{
        Enabled = $true
        Obfuscate = $false
        HideConsoleWindow = $false
        RequireElevation = $false
        PackageType = 'Console'
        Platform = 'x64'
        RuntimeIdentifier = 'win10-x64'
        PowerShellVersion = 'Windows PowerShell'
        Host = 'IronmanPowerShellHost'
        DotNetVersion = 'v4.8.0'
        ProductVersion = ''
        FileVersion = ''
        FileDescription = ''
        ProductName = ''
        Copyright = ''
        CompanyName = ''
        ApplicationIconPath = '...\ico\some.ico'   # <- commenting this out will prevent the executable from throwing the error
    }
    Bundle = @{
        Enabled = $true
        Modules = $true
        NestedModules = $true
        # IgnoredModules = @()
    }
}
```

I've included a working executable (test-working.exe.) and one where the error is thrown (test.exe).

[test.zip](https://github.com/ironmansoftware/issues/files/10568011/test.zip)

EDIT: I think this error is also thrown when using `Host = 'IronmanPowerShellWinFormsHost'`, but the console is never opened so the error can't be seen (which is what I ran into initially).
EDIT2: To be clear, the paths used are all absolute paths.
