### ISSUE TITLE
Default admin account automatically restored if deleted

### ISSUE THREAD

**Issue by tkmoeller** [ironmansoftware/powershell-universal#2037]
### Steps to Reproduce

I have a new fresh installed PSU instans running.

1. I have created a new user/identity with username "CustomExample" and the role "Administrator".
2. I log out and in with the new account - all good.
3. I then delete the bultin admin account because I don't want an account with a generic name like "Admin".

The admin account is removed succesfully, but if I restart the PSU service I am then prompted on the login page that authentication has not been setup and I can now login with admin/admin.
Under identities the admin account has now reappeared together with the custom account.

### Expected behavior

```console
Account should be deleted.
```

### Actual behavior

```console
It is deleted, but reappears after service restart.
```

### Environment data

3.7.9

### Visuals

![image](https://user-images.githubusercontent.com/26480631/216276749-f051b5fa-19f5-46bc-b6d1-bf74cf04bc91.png)

**Comment by ksl28** [comment]
I can confirm, that i have the same issue. Running the exact same build.
The admin account is present once again, but the password is at least not changed back to default.

**Comment by donlent** [comment]
From my understanding this is the (current) default of PSU since it must have some sort of fallback mechanism and guarantee that you can always login in case you would lock yourself out. Indeed I also realized that the local identities take always precedence over the effective forms auth that you may do for example by checking AD creds... 
So lets say you have a user in AD that is also called "admin", in case you have a function to check that the local "admin" will win.

**Comment by adamdriscoll** [comment]
PSU will no longer create the admin account if another local account is defined with the administrator role. This effectively allows you to rename the admin account without it coming back.
