### ISSUE TITLE
Set-PSUIdentity fails with a 405 Error

### ISSUE THREAD

**Issue by zac-driscoll** [ironmansoftware/powershell-universal#2085]
### Steps to Reproduce

$DogID = Get-PSUIDentity -Name "Bug"
Set-PSUIdentity -Identity $DogID -Name "Austin"

### Expected behavior

```console
Should change the name of the identity.
```

### Actual behavior

```console
Returns a 405 Error
```

### Environment data

Powershell Universal 3.8

**Comment by donlent** [comment]
...and since you'll hopefully take care of that, could you please also allow to Set the Password? 😁

For example:
`Set-PSUIdentity -Identity $Identity -Password "myNewPassword" `
This would indeed also solve my former issue mentioned here:
https://github.com/ironmansoftware/issues/issues/1879

Thanks!

**Comment by adamdriscoll** [comment]
@donlent - We'll get that added in 3.8.
