### ISSUE TITLE
functions in scope not working in dynamics

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2231]
### Steps to Reproduce

when i use a function outside of a dynamic that is not in a module the dynamic wont see the function

### Expected behavior

```console
no cannot find cmdlet error
```

### Actual behavior

```console
cannot find x cmdlet
```

### Environment data

PSU: 3.8.3
IIS: Nested

**Comment by adamdriscoll** [comment]
This problem is a little more involved than I thought at first. I also do not believe this is actually a new problem but much easier to encounter now that we have the page editor. 

In the meantime, I'm sure you are aware of the workarounds but I will leave them here in case any one else runs into this issue. 

## Define the function at the dashboard level 

Dashboard.ps1
```
function Get-TestFunc {
New-UDTypography "Test"
}

New-UDDashboard -Pages @(
         Get-UDPage -Name 'Page'
)
```

Page.ps1
```
New-UDDynamic -COntent {
Get-TestFUNC
}
```

## Define the function in a variable using a script block 

This isn't as nice

Page.ps1
```
$Functions = @{
    Func1 = {
        New-UDTypography -Text "Test"
    }
}

New-UDDynamic -Content {
    & $Functions.Func1
}
```

## Define the function in a module 

Use the module feature to define this function and it will be imported automatically.

**Comment by Omzig** [comment]
> This problem is a little more involved than I thought at first. I also do not believe this is actually a new problem but much easier to encounter now that we have the page editor.
> 
> In the meantime, I'm sure you are aware of the workarounds but I will leave them here in case any one else runs into this issue.
> 
> ## Define the function at the dashboard level
> Dashboard.ps1
> 
> ```
> function Get-TestFunc {
> New-UDTypography "Test"
> }
> 
> New-UDDashboard -Pages @(
>          Get-UDPage -Name 'Page'
> )
> ```
> 
> Page.ps1
> 
> ```
> New-UDDynamic -COntent {
> Get-TestFUNC
> }
> ```
> 
> ## Define the function in a variable using a script block
> This isn't as nice
> 
> Page.ps1
> 
> ```
> $Functions = @{
>     Func1 = {
>         New-UDTypography -Text "Test"
>     }
> }
> 
> New-UDDynamic -Content {
>     & $Functions.Func1
> }
> ```
> 
> ## Define the function in a module
> Use the module feature to define this function and it will be imported automatically.

ty for the work around, i hope you find a solution to the problem ;)
it sure is not intuitive what is going on there ;)

**Comment by Omzig** [comment]
did this make it into 3.8.7? because it went poof from the milestone without any audit ;)

**Comment by adamdriscoll** [comment]
With the addition of the module editor for apps, I'm not going to worry about this and suggest that instead.
