### ISSUE TITLE
Editor sometimes thinks you are in edit mode

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2248]
### Steps to Reproduce

when i go into a dashboard and then refresh, sometimes the editor says it is unsaved

### Expected behavior

```console
no save should be saved
```

### Actual behavior

```console
no save causes things to be unsaved
```

### Environment data

PSU: 3.8.5
IIS: Nested

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/editor-is-unsaved-when-not-using-the-editor/8935/2

**Comment by Omzig** [comment]
I am still seeing this in 3.8.8 :(

#reopen, @adamdriscoll, you can refile this in another release if you want, just moved it to current since it is still an issue ;)


1) edit a dashboard or edit a page in a dashboard
2) Hit F5 to refresh
3) code is now unsaved
  ![image](https://user-images.githubusercontent.com/1987296/230391571-2da13d03-34cc-474f-973b-caa9a3366b17.png)
4) click reload
  ![image](https://user-images.githubusercontent.com/1987296/230391909-1e272440-471d-4b08-8e8b-baef61e61b4c.png)
5) go back to step 2 and repeat the processes until the page tells you it is no longer unsaved

i cannot find any api calls that show the condition as unsaved :(

**Comment by adamdriscoll** [comment]
We changed how changes were detected in the editor. Before, it was checking if the text model had changed in the editor. This is problematic because non-user interaction (like loading data) can cause the model to change after the page has loaded. Instead, we are using the KeyUp event to signal when the editor is unsaved so it requires a user to interact with the editor before marking it as unsaved.
