### ISSUE TITLE
Dashboard Save Can take forever, 30+ seconds

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2276]
### Steps to Reproduce

Click save

### Expected behavior

```console
save
```

### Actual behavior

```console
save takes forever
```

### Environment data

PSU: 3.8.8
IIS: Nested

### Visuals

![2023-04-04_09-07-49](https://user-images.githubusercontent.com/1987296/229819580-000ef145-5985-4e2d-848a-0166b52d0d4e.gif)

**Comment by realslacker** [comment]
I have this issue throughout PSU. On Scripts, script settings, everywhere and it has been happening for me since 2.x days.

**Comment by adamdriscoll** [comment]
Can one of your guys open a support case for this? I want to get some more logs.

**Comment by Omzig** [comment]
@realslacker, my performance has been improving, or i have not been hitting the area where this is a problem. @realslacker you might be the one that needs to create the support case since i have having trouble reproducing it right now on 3.8.9

**Comment by adamdriscoll** [comment]
@Omzig We've made a tweak to this in 3.8.10. The "auto deploy" part of the save happens in a background thread. This means the file is saved immediately and then queued up to be deployed. The dashboard will enter a deploying state and once that's complete, will transition to Started. 

I was able to reproduce really long saves with something like this: 

```
Start-Sleep 10
New-UDDashboard -Content {}
```

This is easy to spot but a lot of people put initialization code above the dashboard call and it might not be obvious that it's causing a slow down. 

I'm not convinced this is the root problem here but it seemed like a much better experience. I have a call with @realslacker tomorrow to check out what is happening with his environment. 

Do note that saving other things can cause auto-deploys as well. For example, saving environments and variables cause an auto-deploy to happen because it may affect how the dashboard is executed. This change will greatly improve the saving of those types of resources in 3.8.10.
