### ISSUE TITLE
Dashboard/App goes to sleep; onClick stops working after x time

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2306]
### Steps to Reproduce

when i let a dashboard go to sleep for a few minutes, it will stop responding to clicks, some times a button will work, but urls and navigation stops working

### Expected behavior

```console
clicking something works
```

### Actual behavior

```console
clicking something does nothing
```

### Environment data

PSU: 3.8.9-current
IIS: Nested
Has happened in the past, but was fixed in the past, seems to have came back at some point.

### Workaround
F5, now you can click

**Comment by Omzig** [comment]
@adamdriscoll, is this something we could get in 4.0?

**Comment by Omzig** [comment]
- I think this issue is related https://github.com/ironmansoftware/issues/issues/2358

**Comment by adamdriscoll** [comment]
Bumping as I cannot yet reproduce.

**Comment by adamdriscoll** [comment]
I'm still having a hard time reproducing this. Can you please create an app like this? 

```
New-UDApp -Title 'PowerShell Universal' -Content {
    New-UDDynamic -Content {
        New-UDTypography -Text "Connection ID: $ConnectionId" -Variant h6
        New-UDTypography -Text "Session ID: $SessionId" -Variant h6
        New-UDTypography -Text "Page ID: $PageId" -Variant h6
        New-UDTypography -Text "Session Timestamp: $($Session.LastTouched)" -Variant h6
        New-UDTypography -Text "Page Timestamp: $($Session.Pages[$PageId].LastTouched)" -Variant h6
    } -Id "SessionInformation"

    New-UDButton -Text 'Refresh' -OnClick {
        Sync-UDElement -Id 'SessionInformation'
    }

}
```

I'm curious if you can let this run and try to reproduce. I'm curious if the app times out and what values change in this set.

**Comment by Omzig** [comment]
there really isn't a way to get a button to work on the client side, because the powershell runs on the server side

**Comment by adamdriscoll** [comment]
Right. I mostly added the button so you could ensure the page was no longer working. I'm curious about the values displayed before and after you press F5.

**Comment by Omzig** [comment]
Page Load:
```
Connection ID: YmLX2ANGLXe2kDGRAmxraA
Session ID: 2ce470e4-8cdc-4596-aded-9928bbcb818c
Page ID: e1b14da7-5317-40a0-a17d-6f7049e8b5ac
Session Timestamp: 10/30/2023 16:49:20
Page Timestamp: 10/30/2023 16:49:20
```

Button Click:
```
Connection ID: YmLX2ANGLXe2kDGRAmxraA
Session ID: 2ce470e4-8cdc-4596-aded-9928bbcb818c
Page ID: e1b14da7-5317-40a0-a17d-6f7049e8b5ac
Session Timestamp: 10/30/2023 16:49:30
Page Timestamp: 10/30/2023 16:49:30
```

**Comment by Omzig** [comment]
Just a tad bit more information. It seems to happen a lot, when i am working in 2 different dashboards and i go back to the other one before i get the timeout popup.

**Comment by adamdriscoll** [comment]
Can you add this to your page as well? 

```powershell
        New-UDTypography -Text "Page Count: $($Session.Pages.Length)" -Variant h6
```

I ask because we have a 5-page limit for each session per dashboard. That means if you have 5 tabs open to the same dashboard and then open a 6th page, the oldest page will be removed from the session's list of pages. We do this to limit memory growth because it's possible to open and close tabs over and over again and we need to do some clean up before the session timeout. IDK if you tend to have a lot of tabs opening or if this just happens kind of randomly. 

That said, I would expect to see a "Session expired" message or whatever when the page state is removed on the tab expires.

**Comment by Omzig** [comment]
First Page Load:
```
Connection ID: RR4iineOxkxEZMfy6syGIQ
Session ID: 2ce470e4-8cdc-4596-aded-9928bbcb818c
Page ID: 90894d27-7c16-40f6-a57d-da945b020505
Session Timestamp: 10/30/2023 17:00:56
Page Timestamp: 10/30/2023 17:00:56
Page Count: 1
```
6th Page Load:
```
Connection ID: i-ECrfj6MOMwOAbR16-_8w
Session ID: 2ce470e4-8cdc-4596-aded-9928bbcb818c
Page ID: f8b8da79-6615-468f-b359-ff24f24a1b9a
Session Timestamp: 10/30/2023 17:01:15
Page Timestamp: 10/30/2023 17:01:15
Page Count: 1
```

The api call is no longer happening when i click the button:
https://servername.com/psu/api/internal/component/element/SessionInformation
First Page Refresh Button:
```
Connection ID: RR4iineOxkxEZMfy6syGIQ
Session ID: 2ce470e4-8cdc-4596-aded-9928bbcb818c
Page ID: 90894d27-7c16-40f6-a57d-da945b020505
Session Timestamp: 10/30/2023 17:00:56
Page Timestamp: 10/30/2023 17:00:56
Page Count: 1
```

Tab 2 still works:
```
Connection ID: Ptxca02ofXGUTDlvce7W-w
Session ID: 2ce470e4-8cdc-4596-aded-9928bbcb818c
Page ID: 666ea78d-a92d-408f-a9d8-2ac0f239b89c
Session Timestamp: 10/30/2023 17:07:02
Page Timestamp: 10/30/2023 17:07:02
Page Count: 1
```

**Comment by Omzig** [comment]
So apparently i must be closing and reopening tabs, but then when the Page count hits 5+, the old page is retired and there is no refresh page popup! you figured it out!

I close and reopen tabs sooooooooooooo much during the day....

**Comment by adamdriscoll** [comment]
This is a bit of a weird problem that was introduced when Edge, Chrome and mobile browsers started sleeping tabs. We used to rely on SignalR''s OnDisconnect event to clean up data when the tab was closed. The problem is that browsers that sleep tabs also cause this to happen so when the user goes back to use the tab, it also no longer works. 

We had picked 5 as an arbitrary number and didn't hear about anyone having problems with it but now, I understand the issue and maybe it's affecting folks, and we just don't know. 

Let me think a bit about how to handle this. It could be possible to just turn off this behavior and let the session timeout take care of cleaning up sessions but could be a problem in busy environments based on user behavior.

**Comment by Omzig** [comment]
Thank you for trying to figure out a possible solution to this. It has been happening for a while, it just took me a really long time to get fed up with it enough to ask for it to be fixed.

It is a shame there is not a 'resume' session. Because F5 can wipe out things you have done on the page.

**Comment by adamdriscoll** [comment]
We don't resume session pages because we are clearing all the state in the background to reduce the memory usage so there would be nothing to resume from. That said, I think this could be more intelligent. Like we don't even check if the user is actively using other tabs so it seems like we should at least put some more logic in there to figure out whether we should actually be clearing the page state. 

I'm going to add an environment variable (PSU_APP_PAGE_MAX) for 4.1.8 to increase the max number of pages as a temporary work around. You can set it to like 10000 or something and likely no longer run into the issue but it will still default to 5. 

This is just temporary while we figure out a better solution.

**Comment by Omzig** [comment]
right, i was just thinking out loud with my fingers on that one :P, thank you for letting me bump that, who knows, they might not see this in production under normal usage. It is probly just us development guys that open and close tabs all the while working said issue. i might bump production to 10 just as a safety precaution.

**Comment by Omzig** [comment]
Installed 4.1.8 and set PSU_APP_PAGE_MAX  to 50, and it is still at 5 connections. i cannot get more than 5 :(

**Comment by Omzig** [comment]
@adamdriscoll, did this get merged?

**Comment by adamdriscoll** [comment]
Yep. I just tested it again. 

```
    New-UDTypography $ENV:PSU_APP_PAGE_MAX -Variant h5
    New-UDTypography $Session.Pages.Count -Variant h5
```

![image](https://github.com/ironmansoftware/issues/assets/1256531/2d4fb805-6ec0-4a9c-917c-d94ffd25e37a)


Just refreshing the page is incrementing the page count past 5.

**Comment by Omzig** [comment]
so i still cannot get more than 5.... I pulled up 6 tabs:

Tab 1 Refresh:
```
Connection ID: dRZpxZpHFCdMb-kSuyHbOg
Session ID: c0a247af-1b28-4581-8913-0b2a78992f73
Page ID: e07fcce0-537a-48cf-ab43-dc9cd2068c0e
Session Timestamp: 11/03/2023 17:50:00
Page Timestamp: 11/03/2023 17:50:00
Page.Length: 1
PSU_APP_PAGE_MAX: 50
Session.Pages.Count 5
```
Tab 2 Refresh:
```
Connection ID: o2rK0NrWodVLBu-x1zbfuQ
Session ID: c0a247af-1b28-4581-8913-0b2a78992f73
Page ID: 66207c27-c509-457e-a51f-1d3b5771c5ab
Session Timestamp: 11/03/2023 17:50:04
Page Timestamp: 11/03/2023 17:50:04
Page.Length: 1
PSU_APP_PAGE_MAX: 50
Session.Pages.Count 5
```
Tab 3 Refresh:
```
Connection ID: glU3Zyx1-efWwpMUYXTBMQ
Session ID: c0a247af-1b28-4581-8913-0b2a78992f73
Page ID: 299b5d6b-f588-484e-8a71-436c8f430b4f
Session Timestamp: 11/03/2023 17:48:54
Page Timestamp: 11/03/2023 17:48:54
Page.Length: 1
PSU_APP_PAGE_MAX: 50
Session.Pages.Count 1
```
Tab 3 will not refresh :(

**Comment by Omzig** [comment]
SOOOOOOOOOOOOOOOOO, my upgrade did not go soo well, i am reinstalling 4.1.8. Now it is working with the workaround.

Ok, so when does the session Page Count go back down to 1? I closed all the tabs, and it seems the number does not change after that.

```
Connection ID: 21GbfSu4G1TWYbdPgxpDhA
Session ID: 83faa2ab-7e6e-462b-9e81-639def6b74d4
Page ID: d78334d7-0afd-415e-9a4b-4aebe56a50cb
Session Timestamp: 11/03/2023 19:52:35
Page Timestamp: 11/03/2023 19:52:35
Page.Length: 1
PSU_APP_PAGE_MAX: 50
Session.Pages.Count 15
```

# Crazy:

So, when i hit refresh after 50, it keeps all 6 of my tabs working, but then maxes out at 50 on each tab and it is still working:

```
Connection ID: sxYA6tXDSQFzZvUGg7f9lg
Session ID: 83faa2ab-7e6e-462b-9e81-639def6b74d4
Page ID: e43c0a4b-cd63-4064-b944-1bfd338163f8
Session Timestamp: 11/03/2023 19:56:55
Page Timestamp: 11/03/2023 19:56:55
Page.Length: 1
PSU_APP_PAGE_MAX: 50
Session.Pages.Count 50
```

@adamdriscoll, Do we close this and open another task to handle a better fix or just keep this one open?

**Comment by Omzig** [comment]
# Workaround
PSU_APP_PAGE_MAX =50

**Comment by adamdriscoll** [comment]
Seems like we have a workaround.  Feel free to reopen if you don't agree.
