### ISSUE TITLE
IIS WebSocket Feature Enabled	SERVERNAME      Not running in IIS.

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2313]
### Steps to Reproduce

i am running in IIS for said servername
https://servername.domain.com/Beta/admin/health

### Expected behavior

```console
Running in IIS.
```

### Actual behavior

```console
Not running in IIS.
```

### Environment data

PSU: 4.0.0 BETA 2
https://imsreleases.blob.core.windows.net/universal-nightly/4694969633/release.md

**Comment by adamdriscoll** [comment]
I can't reproduce this one. 

<img width="662" alt="image" src="https://user-images.githubusercontent.com/1256531/232135244-47fd758e-cae6-4d7c-883e-526841165513.png">

We check to see if the APP_POOL_ID environment variable is defined in order to determine whether to run this. It should be defined by IIS. It's the same check we use throughout the app.

**Comment by adamdriscoll** [comment]
![image](https://user-images.githubusercontent.com/1256531/236013667-3b38691c-0364-4a61-a6af-2caef3f5f3d4.png)

**Comment by adamdriscoll** [comment]
Added a new check for ASPNETCORE_IIS_PHYSICAL_PATH as this env var seems to appear in all the PSU instances I checked.
