### ISSUE TITLE
Git Sync Pull failed to bring code from the hard drive into memory

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2335]
### Version

3.8.10

### Severity

High

### Steps to Reproduce

i am experiencing an issue with the git pull process, it did not pull the code on the hard drive into memory
1. make a change on dev
2. commit
3. PR dev into main
4. wait 1 min
5. check prod for changes (change on the HD are there) (Changes in the /admin site are still showing old code)

### Expected behavior

```console
new code should be running
```

### Actual behavior

```console
old code is running
```

### Additional Environment data

IIS: Nested

### Related
- https://github.com/ironmansoftware/issues/issues/1984

### Workaround

Restart app pool

**Comment by adamdriscoll** [comment]
@Omzig - Is it everything or only certain resources?

**Comment by schubfre** [comment]
It seems to affect everything - Published Folders, APIs, Scripts. It seems to me that the filesystem watcher is not working correctly.

Also the changes are visible in the actual filesystem AND under Settings/Configurations. The only place where the changes are not visible are their respective categories (APIs/Endpoints, Automation/Scripts, etc), which also has the effect, that they won't be implemented into running PSU.

There are currently two workarounds:

- Restart PSU service (not really viable in a prod env)
- Enable edit mode, edit an affected file (for example add a space) via their category (editing it via Settings/Configurations will not work!), save the file and then exit edit mode via the discard button. This seems to trigger the filesystem watcher.
- I know Enabling edit mode in a prod, One-Way env is not possible, therefore for this workaround to work, I enabled Two-Way mode, made the above steps and then enabled One-Way again

**Comment by adamdriscoll** [comment]
Ok. I will dig in. We actually disable the file system watcher when loading from git sync because we know which files have changed based on the git history. 

I'll circle back to let you know if I need some more info.

**Comment by adamdriscoll** [comment]
I can't immediately reproduce this so some logs would be helpful; especially with the debug level set. 

My current test configuration:

Git one-way sync from github, internal git client
Edit scripts.ps1 (change description of script)
Force git sync 
Reload scripts page 
See that description has changed 

I'll continue to mess around and see if I can reproduce. 

EDIT: Reproduced with endpoints

If an endpoint uses -Path and you change the file at that path, the endpoint will not update until I update endpoints.ps1. 

EDIT2: Current tests

I've been switching between forcing a git sync and letting it run on the schedule. 

- Environments: Success
- Endpoints: Failure
- Scripts: Success
- Schedules: Success
- Published Folders: Success
- Dashboards: 
    - dashboard.ps1: Success  
    - pages\Page.ps1: Failure 
- Roles: Success
- Variables: Success

**Comment by schubfre** [comment]
> Ok. I will dig in. We actually disable the file system watcher when loading from git sync because we know which files have changed based on the git history.
> 
> I'll circle back to let you know if I need some more info.

This is interesting info, because it explains at least my problem with the published folder I had recently.
I created a published folder via GUI, then edited it via Settings/Configurations, but the changes didn't populate to the GUI version of the published folder.
If the filesystem watcher is disabled, when git sync is enabled. Then this isn't a problem.

The only definitive problems in regards to git sync I had were with endpoints (as you said, we use 'external' endpoints via the -Path parameter) and with scripts.

Do you  still need logs? I can't say when I'll be able to reproduce this issue. Maybe @Omzig can produce some logs.

Regarding your test config, we rarely change properties of scripts or APIs, so I can't say anything about that. But the content of these has the aforementioned problem.

**Comment by Omzig** [comment]
> Regarding your test config, we rarely change properties of scripts or APIs, so I can't say anything about that. But the content of these has the aforementioned problem.

we have seen this in prod when we update an api and a dashboard at the same time, then the editor still shows the old api code, while the HD shows the new code. 

In Dev with Two-Way Sync:
- if i edit a file with vscode, when should PSU know that the file has been updated, lets say for the api's at least? This happens when we need to refactor and do a find an replace.

**Comment by adamdriscoll** [comment]
Are you editing the files in VS Code using the PSU extension or on disk? 

EDIT: We've introduced a fix for the endpoints -path parameter not reloading. It will be in tonight's nightly.

**Comment by Omzig** [comment]
> Are you editing the files in VS Code using the PSU extension or on disk?
> 
> EDIT: We've introduced a fix for the endpoints -path parameter not reloading. It will be in tonight's nightly.

vscode on the HD, i have had too many issues with the vscode plugin messing up my code. I have not had a chance to figure out what my problem is and recreate it and get an issue in for it.

**Comment by adamdriscoll** [comment]
I've made a change to how configuration files are loaded. Rather than running on multi threads to attempt to load files in tandem, they are now put onto a queue to process in series. The problem was that the file system watcher was firing multiple times per file change at the same time the git sync was attempting to read the same files. We had some checks in place to make sure we weren't reading the same file multiple times (SHA checksums of the content) but with many threads running at once, I have to imagine there was some sort of race condition leading to these issues with git sync and the file system watcher. 

Feel free to try a nightly build to verify in your environment. This will be included in 3.8.12.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/dashboard-pages-not-showing-changes-in-ui/9083/2

**Comment by Omzig** [comment]
> I've made a change to how configuration files are loaded. Rather than running on multi threads to attempt to load files in tandem, they are now put onto a queue to process in series. The problem was that the file system watcher was firing multiple times per file change at the same time the git sync was attempting to read the same files. We had some checks in place to make sure we weren't reading the same file multiple times (SHA checksums of the content) but with many threads running at once, I have to imagine there was some sort of race condition leading to these issues with git sync and the file system watcher.
> 
> Feel free to try a nightly build to verify in your environment. This will be included in 3.8.12.

@adamdriscoll 
Would it make sense to turn the file watcher off when you do the git sync changes then turn the file watcher back on?
