### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'create')

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#2361]
### Version

3.8.10

### Severity

High

### Steps to Reproduce

Making a minimal change to a script (e.g. updating its description) under certain conditions* can result in PSU throwing the below error:

```
TypeError: Cannot read properties of undefined (reading 'create')
    at I (editor.main.js:2:1116428)
    at O.setValue (editor.main.js:2:1120873)
    at M.setValue (editor.main.js:2:1826392)
    at Editor.js:74:25
    at Al (react-dom.production.min.js:262:359)
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Wa (react-dom.production.min.js:122:325)
    at Ll (react-dom.production.min.js:261:308)
    at ml (react-dom.production.min.js:243:50)
    at react-dom.production.min.js:123:115
```

* The conditions are not included here

### Expected behavior

```console
Editing a script should never result in a React error
```

### Actual behavior

```console
Editing a script (under certain conditions) may result in a React error
```

### Additional Environment data

PSU 3.8.10

Support Ticket 5309

**Comment by adamdriscoll** [comment]
Cannot reproduce in new versions.

**Comment by adamdriscoll** [comment]
Customer is reporting this issue on 4.1

**Comment by adamdriscoll** [comment]
Still not handled...

**Comment by insomniacc** [comment]
I'm seeing this in 4.2.12, I made changes to my script settings, click to save, then click to run (sometimes it just happens when I click to run with no changes) and instead of going to the job screen I get this error:

![image](https://github.com/ironmansoftware/issues/assets/10046621/bbcafb3d-92cc-4cfc-b26e-cea1574709b0)

It seems non-impacting though thankfully, doesnt cause any issues other than a UI glitch, and navigating to the page after this error is thrown everything looks fine.

**Comment by adamdriscoll** [comment]
We just rolled another fix for this. Hopefully it is finally resolved.
