### ISSUE TITLE
Rerun Job with String Array

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2434]
### Version

3.9.4

### Severity

Low

### Steps to Reproduce

https://forums.ironmansoftware.com/t/rerun-job-issue/9195/2

### Expected behavior

```console
Rerun with stirng array works
```

### Actual behavior

```console
Rerun with string array does not work.
```

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/rerun-job-issue/9195/2

**Comment by realslacker** [comment]
I am also seeing this issue, and a related issue where the correct parameters aren't show when clicking the Rerun Job button if there are multiple parameter sets.

Example Param Block
```powershell
[CmdletBinding( DefaultParameterSetName = 'Multiple' )]
param(

    [Parameter( Mandatory )]
    [string]
    $Server,

    [Parameter( Mandatory )]
    [string]
    $Partition,

    [string]
    $TargetOU,

    [Parameter( ParameterSetName = 'Single' )]
    [string]
    $EmployeeNumber,

    [Parameter( ParameterSetName = 'Multiple' )]
    [switch]
    $FullSync,
    
    [ValidateSet( 'name', 'path', 'displayname', 'givenname', 'sn', 'mail', 'employeeid', 'employeenumber', 'userprincipalname', 'samaccountname' )]
    [string[]]
    $PropertiesToKeepOnUpdate,

    [bool]
    $StandardizeUserNames,

    [switch]
    $NoDelete,

    [switch]
    $ShowDetail,

    [switch]
    $DryRun

)
```

Issues with this example:
1. Clicking Rerun Job will always open to the DefaultParameterSet
2. Because the $EmployeeNumber parameter comes first it is shown even though the it should show $FullSync, toggling the parameter set shows the right options
3. $PropertiesToKeepOnUpdate has same issue as OP in linked thread, it will default to an empty string

**Comment by adamdriscoll** [comment]
We should also look into this while we're at it: https://forums.ironmansoftware.com/t/string-arrays-param/8420
