### ISSUE TITLE
Endpoint Docs with -Path

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2464]
### Version

3.9.4

### Severity

Low

### Steps to Reproduce

https://forums.ironmansoftware.com/t/swagger-documentation-when-path-is-used/9265

### Expected behavior

```console
Docs are shown
```

### Actual behavior

```console
Docs are not shown.
```

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/swagger-documentation-when-path-is-used/9265/2

**Comment by jpbruckler** [comment]
@adamdriscoll this can be closed. I was initially using `New-PSUEndpoint -Method GET -url "ad/user" -Environment "AD-7.3.4" -Documentation "ActiveDirectory" -Path  (Join-Path $Repository 'iam\apis\aduser.ps1')`  

Switching to using `$PSScriptRoot` instead of `$Repository` has resolved the issue.
`New-PSUEndpoint -Method GET -url "ad/user" -Environment "AD-7.3.4" -Documentation "ActiveDirectory" -Path (Join-Path $PSScriptRoot '..\iam\apis\aduser.ps1')`

Repository structure is below. The way I was reading the documentation I was thinking that the `$Repository` variable was available for configuration, not just at runtime.

```
C:.
├───.universal
├───dashboards
│   ├───ActiveDirectory
│   │   └───Pages
│   ├───New Package
│   └───PowerShell Packages
├───genscripts
├───iam
│   ├───apis
│   ├───assets
│   │   └───images
│   ├───Classes
│   ├───Functions
│   ├───lib
│   └───tests
└───Modules
    ├───Send-MailkitMessage
    └───WritePSUlog
        └───1.0.0
```

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/swagger-documentation-when-path-is-used/9265/3

**Comment by adamdriscoll** [comment]
@jpbruckler - Thanks for circling back. I actually found a different issue while trying to reproduce this. :)
