### ISSUE TITLE
PSU 4.0.1 - New-UDIconButton are missin md in Size

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#2470]
### Version

4.0.0

### Severity

Quality-of-life

### Steps to Reproduce

I do high rate this bug as I have multiple New-UDIconButton and as they are set to -Size md the won't work.
And it causing issues to the degree that I can't migrate to PSU 4

### Expected behavior

```console
New-UDIconButton should have size md
```

### Actual behavior

```console
New-UDIconButton throws error as md are missing in -size
```

**Comment by rwidmark** [comment]
@mattselle @adamdriscoll was this fixed in 4.0.2? Can't find it in the release notes.

**Comment by mattselle** [comment]
It did not make it in. I should have it done this week and it will be in next release

**Comment by adamdriscoll** [comment]
I just looked at this and we do a have medium size defined for New-UDIconButton and it is the default value. 

```
        [Parameter()]
        [ValidateSet('small', 'medium', 'large')]
        [string]$Size = 'medium'
```

This also matches the IconButton props. 

https://mui.com/material-ui/api/icon-button/#props

This is the same value set as in v3 so I'm going to mark this as closed because it shouldn't be preventing an upgrade to v4 from v3. If I'm not understanding, please correct me.
