### ISSUE TITLE
API Endpoint implementing DELETE requires ContentType to be specified

### ISSUE THREAD

**Issue by realslacker** [ironmansoftware/powershell-universal#2612]
### Version

3.9.16

### Severity

Low

### Steps to Reproduce

I have an API endpoint that implements GET, POST, and DELETE. When I submit a GET or POST request using Invoke-RestMethod (PS7) with the -Body parameter it works as expected without specifying the -ContentType. When I submit a DELETE request with a body I have to also include 'application/x-www-form-urlencoded' as the content type or the parameters will not be bound.

I'm not sure if this is because of the implementation of Invoke-RestMethod or PSU.

### Expected behavior

```console
PS> Invoke-RestMethod -Uri 'https://some.site/endpoint' -Body @{ Param = 'Value' } -Method DELETE
OK
```

### Actual behavior

```console
PS> Invoke-RestMethod -Uri 'https://some.site/endpoint' -Body @{ Param = 'Value' } -Method DELETE
Invoke-RestMethod: Cannot process command because of one or more missing mandatory parameters: Param.
at , : line 1

PS> Invoke-RestMethod -Uri 'https://some.site/endpoint' -Body @{ Param = 'Value' } -Method DELETE -ContentType 'application/x-www-form-urlencoded'
OK

PS> Invoke-RestMethod -Uri 'https://some.site/endpoint' -Body (ConvertTo-Json @{ Param = 'Value' }) -Method DELETE -ContentType 'application/json'
OK
```

### Additional Environment data

Windows 10 with PowerShell 7.3

**Comment by adamdriscoll** [comment]
Looks like Invoke-RestMethod only sets the content type by default if it's a POST. 

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-7.3#-contenttype

It's a bit funny because it formats the body with this content type anyways but doesn't sent the Content-Type header. We've made PSU assume the content type and try to read the form data if content type isn't set.
