### ISSUE TITLE
Unable to get published folders to work with NestedIIS website

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2655]
### Version

4.2.21 and 5.0.0-beta4

### Severity

Low

### Steps to Reproduce

https://docs.powershelluniversal.com/platform/published-folders

### Expected behavior

```console
downloads to work
```

### Actual behavior

```console
Page Not Found
```

### Additional Environment data

IIS: Nested

**Comment by Omzig** [comment]
can we slip this into the next minor release?

**Comment by adamdriscoll** [comment]
@Omzig - I can't reproduce this per se. I did find a bug in the process. 

First, I tried a path with a rooted path. This worked fine. I was accessing the file at: http://localhost/psu1/request/repository/.universal/publiushedFolders.ps1

```
New-PSUPublishedFolder -RequestPath "/request" -Path "C:\src\psu\data1" -DefaultDocument @() -Name "Folder"
```

Second, I tried a relative path. If it's not rooted, it's assumed that the repository is the root. This didn't work because I just specified a slash at the beginning of the path. The resulting path was C:\.universal\publishedFolders.ps1. I was attempting to access the file at: http://localhost/psu1/repo/.universal/publiushedFolders.ps1

```
New-PSUPublishedFolder -RequestPath "/repo" -Path "/.universal" -DefaultDocument @() -Name "Folder1"
```

Finally, I created a published folder that is specific to .universal without a starting slash. This works. 

```
New-PSUPublishedFolder -RequestPath "/uni" -Path ".universal" -DefaultDocument @() -Name "Folder2"
```

I don't think this is related to nested IIS sites because I'm not even seeing the nested path come into the URL that is processing the published folder URL in the debugger. We'll get a fix in for the starting slash issue and please let me know if you are still running into this after the update.

**Comment by Omzig** [comment]
This is still a problem, would you like a support ticket or setup a call to see the problem first hand? Even the copy button leaves the nested site name out of it.

**Comment by adamdriscoll** [comment]
@Omzig - We should schedule a call because I still can't reproduce this. I fixed the issue with the copy button but the published folder works fine.

**Comment by Omzig** [comment]
> @Omzig - We should schedule a call because I still can't reproduce this. I fixed the issue with the copy button but the published folder works fine.

cool, maybe we can lump it into the other support ticket. who knows, maybe i did something dumb.

**Comment by Omzig** [comment]
funny thing, the copy button now puts the site name in the wrong place:

```
/psuSandbox/https://dev.psu.domain.com/assets
```
