### ISSUE TITLE
Replace Desktop with Progressive Web App 

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2756]
### Summary of the new feature / enhancement

Universal Desktop is a bit of an ugly stepchild at the moment.

- Only works on Windows
- Completely different installer 
- Weird authentication setup 
- Can't connect to remote systems and runs locally. 

We should replace it with a PWA: https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/

I already have PSU 4.2 working as a PWA but we can add more features to align with the current implementation of Desktop. 

The following will need to be done: 

- [ ] Convert Desktop features to plugin for easy customization
- [ ] Implement a Window process so that we can do things that Desktop currently does within the desktop app
- [ ] Implement PWA features like notifications and badges 
- [ ] Reconsider the current authentication setup for Desktop 
- [ ] Extend the current installer to run as a Per User install that would effectively install PSU as a desktop process

**Comment by rwidmark** [comment]
Something that would be great is this but with a connection to external PSU server.
It can also work as an agent for the server to the client.

User login against the server then it's an app that showing the GUI from the server instead of a browser.

For extra security you can add some kind of access right where you can write in for example hostname, ip or Mac for the clients that has the rights to have "agent" access.

**Comment by adamdriscoll** [comment]
This works from an external app as well as a local one. So you could already install PSU as a PWA for a remote server. 

That said, with the agent idea, that is also possible. We could have a similar connection model as with event hubs and treat it as another PSU instance if it has all the elements installed locally.

**Comment by adamdriscoll** [comment]
We don't really need this. What we really need is to have PSU install and run in the user scope and then expose some extra features when that's the case.
