### ISSUE TITLE
Script with multiple Boolean parameters will not start and gets stuck in a Queued state

### ISSUE THREAD

**Issue by TurnItOff-OnAgain** [ironmansoftware/powershell-universal#2825]
### Version

4.1.7

### Severity

Low

### Steps to Reproduce

More info here

https://forums.ironmansoftware.com/t/error-and-script-stuck-enqueued-when-run-with-boolean-parameters/9942

This is the entire script

```
param(
    $computer,
    [bool]$bootTimetest,
    [bool]$installDatetest,
    [bool]$resourcestest,
    [bool]$networkTest
)
```

This is the Run prompt. I fill this out completely making everything true and putting a value in the computer parameter

![48f32955ddd19508f7348b1d3952229831714a23](https://github.com/ironmansoftware/issues/assets/26926284/7b66eee3-4869-4e3f-9a06-9ed31aa8129b)

It takes me to the job page where it sits for 5 seconds or so then gives this error page

![b0c076c59b2e954a7317f991644a85d14618a53d](https://github.com/ironmansoftware/issues/assets/26926284/97abf120-4617-4857-b72f-b25662bc96d3)

The script is now stuck in a queued state in both the admin console, as well as hangfire. I have to restart the service to clear it out. The script also cannot be updated from VSCode while stuck queued, but I can edit it in the admin console.

### Expected behavior

```console
Run the script with the expected values
```

### Actual behavior

```console
script fails
```

### Additional Environment data

Universal 4.1.7
Windows Server 2019
Built in web server.

**Comment by adamdriscoll** [comment]
@TurnItOff-OnAgain - This is actually a problem with the computer parameter. New-PSUSchedule already has a -Computer parameter so what ends up happening is that whatever you type in there will result it in queueing on a machine that isn't likely part of the PSU cluster. 

You can rename the parameter to work around this. 

```
param(
    $targetcomputer,
    [bool]$bootTimetest,
    [bool]$installDatetest,
    [bool]$resourcestest,
    [bool]$networkTest
)
```

We are resolving this in v4.2 by pass parameters in as a hashtable rather than dynamic parameters. Dynamic parameters will still work but we are using hashtables by default because of issues like this.

**Comment by TurnItOff-OnAgain** [comment]
That works. Thanks!
