### ISSUE TITLE
A text box is not a text box

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2838]
### Version

4.1.x

### Severity

Low

### Steps to Reproduce

when i type 000010 in my text box, on change thinks it is 10. 

### Expected behavior

```console
0000010 is 0000010
```

### Actual behavior

```console
0000010 is 10
```

### Visuals

![image](https://github.com/ironmansoftware/issues/assets/1987296/a3fec8f3-6467-42cb-bbc4-1495ee41c56c)

**Comment by Omzig** [comment]
@adamdriscoll, do you have a magical workaround?

**Comment by adamdriscoll** [comment]
That's a new one. You can use the $Body variable. It's the raw JSON. 

```
    New-UDTextbox -Id 'textbox14' -OnChange {
    Show-UDToast -Message $Body.Trim('"')
 } -Label 'Name' -Placeholder 'Enter your name' -Value 'John Doe'
```

**Comment by Omzig** [comment]
Work around is working around the problem.

**Comment by adamdriscoll** [comment]
Just a note on why this is happening. When fixing some things with the autocomplete, we added some logic in the back end to convert strings to integers with int.TryParse. The problem is that numbers like 0011100111 pass that check and result in the truncated values. 

We really need to send the expected data type from the client to the server to prevent having to guess what the data type is. We also had this same issue with DateTime objects converting integers into dates because some integers are valid data formats (e.g. file time).

**Comment by Omzig** [comment]
@adamdriscoll, can we also add this one to .14?
