### ISSUE TITLE
Set value (variable) in OneWay gitsync

### ISSUE THREAD

**Issue by timoline** [ironmansoftware/powershell-universal#3125]
### Version

4.2.12

### Severity

Critical

### Steps to Reproduce

We cannot set the value of a variable in the gui when OneWay gitsync is enabled.
(Vault is database)

Also when a variable is defined and vault is database , this is not visible in the GUI...

thx

### Expected behavior

```console
that you can modify the value of a variable
```

### Actual behavior

```console
you cannot modify the value of a variable
```

### Visuals
![image](https://github.com/ironmansoftware/issues/assets/680252/741c8e6f-a772-411c-9b1c-7758562f06e8)

**Comment by schubfre** [comment]
You are trying to modify a public variable which is written into code (variables.ps1). And because it is stored in the ps1 you can't change it in One Way git sync. Only secret variables are stored in the specified database.

This is how the difference looks between secret and public variables
![image](https://github.com/ironmansoftware/issues/assets/28289080/a6f3b390-8bd2-4c3e-ac4a-c22bc4535093)

**Comment by timoline** [comment]
Well, not exactly.
The value is not in the .ps1 file and database = $true..

So the value should be stored in the db and it should be possible to modify it
