### ISSUE TITLE
Log viewer messages are in UTC

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#3142]
### Version

4.2.12

### Severity

Low

### Steps to Reproduce

Log viewer is displaying messages timestamps in UTC. Log messages are stored in the database in UTC but we should translate to local time when viewing them. 

### Expected behavior

```console
Logs are in local time.
```

### Actual behavior

```console
Logs are in UTC.
```

**Comment by JessePeden** [comment]
Thank you for working on this.  I see that the logs do show in local time now, however it appears that this was only changed in the Text view of the logs.  If you look at the Table view, the times are still shown in GMT/UTC, so now it's confusing because of the mismatched outputs.  The issue with using GMT/UTC for log entries is mainly when factoring in DST and needing to always be aware of how many hours to add/subtract on which date, so always showing the logs in the local time accounts for that.
