### ISSUE TITLE
Error Message/Popup without underlying error

### ISSUE THREAD

**Issue by Callidus2000** [ironmansoftware/powershell-universal#317]
**Describe the bug**
I've created an active directory selfservice solution which works flawless. After upgrading from 1.5.21 to 2.1.2 the application itself works without a problem, but the "reset-password" form gets a popup which says "Insufficient access rights to perform the operation". I do not trigger it in my code directly and the underlying UDForm -OnSubmit code throws no error, neither Terminating nor NonTerminating ones.

![image](https://user-images.githubusercontent.com/73584079/126298047-00065ecd-8f6d-42d1-8785-4d1f11d3ac4e.png)

What can be responsible for auto-generating this popups?

**Version**
Version Number: 2.1.2
Operating System:  Win10 and Server 2019

**Logs** 
Nothing logged

**Comment by adamdriscoll** [comment]
Not 100% sure where that would come from if you aren't seeing an error messages within your code. This pop up happens when any error (terminating or not) is returned from executing a script block in UD. 

You can disable these pop ups with this setting: https://docs.powershelluniversal.com/dashboard/dashboards#disable-error-toasts

**Comment by Callidus2000** [comment]
Thanks a lot for pointing to the setting.
I've added a few `-ErrorAction Stop' to some commands in the code and now the error shows up in console as well... Somewhere in the underlying module the error is made very silent... Fixing the base problem now, issue closed...
