### ISSUE TITLE
Rate limiting bug

### ISSUE THREAD

**Issue by mikedhanson** [ironmansoftware/powershell-universal#3420]
### Version

4.3.0

### Severity

High

### Environment

msi

### Steps to Reproduce

Rate limiting doesnt work when you have more than one endpoint selected

Works: 
```
$Parameters = @{
    Endpoint = "GET:*"
    Period   = "00:01:00"
    Limit    = 2
}
New-PSURateLimit @Parameters
```

Does not work: 

```
$Parameters = @{
    Endpoint = "GET,POST:*"
    Period   = "00:01:00"
    Limit    = 2
}
New-PSURateLimit @Parameters
```

Also when you click on the "edit details" pencil next to the rate limit item that takes you to a blank page. 

### Expected behavior

```console
rate limit to work
```

### Actual behavior

```console
does not work
```

**Comment by adamdriscoll** [comment]
This has been resolved. There were 2 problems. One was that the rule was being enforced per HTTP method instead of being grouped. This meant that GETs and POSTs would have different counts for the rate limit. The second issue was that the UI allowed for multiple methods to be selected.  This isn't a valid rate limit rule. You either need to select a method or use * to specify all methods. 

The edit button has also been removed since that doesn't do anything.
