### ISSUE TITLE
Unable to save git settings

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3439]
### Version

5.0.0-beta7 (9637475131)

### Severity

Low

### Environment

Nested IIS

### Steps to Reproduce

when I try to save the git settings, clicking the OK button does nothing

### Expected behavior

```console
Saves
```

### Actual behavior

```console
Does Nothing
```

### Screenshots/Animations

![image](https://github.com/ironmansoftware/issues/assets/1987296/6414f14c-9593-4a45-9e3f-7236ef5e5ce4)

**Comment by adamdriscoll** [comment]
It's due to the fact that database isn't a valid URL.

**Comment by Omzig** [comment]
so you removed the local git repo function?

**Comment by adamdriscoll** [comment]
We removed the git pack functionality that stored the git repo in the database since it was clunky and error prone. We never really had a simple local git repo option but I think that would be a great idea. It would be very easy to implement since we already manage it and would just skip the remote management.

**Comment by adamdriscoll** [comment]
I think there is another issue causing this to not save as well. Will get this fix.

**Comment by adamdriscoll** [comment]
I've fixed the not saving issue and added local git repos. No need for a remote.
