### ISSUE TITLE
/git not working in general

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3480]
### Version

5.0.0-rc2

### Severity

Low

### Environment

Nested IIS

### Steps to Reproduce

when i use the git features, they are not working
- on commit; cannot see check boxes that need to be included in the commit, they are checked; no visual feedback
- commit does not push, i have to do a manual git push
- have to refresh(F5) /git/commit to see new file changes
- missing diff in commits /admin/settings/git
- it is possible that it didn't save my password the right way: https://stackoverflow.com/questions/26145023/libgit2sharp-fetching-fails-with-too-many-redirects-or-authentication-replays

### Expected behavior

```console
git should work as good as it did in v4
```

### Actual behavior

```console
git is rough around the edges
```

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/edf71362-f8c4-40a9-b0d4-f00dc45f9be9)

![image](https://github.com/user-attachments/assets/f9bdb948-351e-4745-ae58-d252e0b6a8f1)

**Comment by adamdriscoll** [comment]
I haven't looked through these issues yet but editing files in Settings \ Files does not stage the file so it looks like there are no changes.

**Comment by adamdriscoll** [comment]
Most of this will be fixed in tonight's nightly. 

- on commit; cannot see check boxes that need to be included in the commit, they are checked; no visual feedback - UI is fixed
- commit does not push, i have to do a manual git push - Fixed
- have to refresh(F5) /git/commit to see new file changes - UI Fixed 
 - missing diff in commits /admin/settings/git - Added back to console 
- it is possible that it didn't save my password the right way: https://stackoverflow.com/questions/26145023/libgit2sharp-fetching-fails-with-too-many-redirects-or-authentication-replays - I can't reproduce this one. Seems to save the credentials fine for me and syncs without those errors 

There are some weird performance\UX issues at the moment when discarding changes that I still need to look into as well.

**Comment by Omzig** [comment]
@adamdriscoll, ty so much!

**Comment by Omzig** [comment]
@adamdriscoll, when there are 2 pages of changes in git save, and you [x] on the check all, it only selects the first page and does not select/check all the items on the 2nd page.
- half of a commit confirmed

**Comment by adamdriscoll** [comment]
Closing this in hopes of smaller issues about git going forward.
