### ISSUE TITLE
Improve Functions Tab to have each cmdlet with its own editor

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3562]
### Summary of the new feature / enhancement

As a developer, I want the functions tab to look like the pages tab so that i can quickly manage all of my shared functions. 
- go to apps
- click functions tab
- click add function
- editor looks like a pages 
- editor can be toggled back to edit all
- functions are then sortable because it uses the same pattern as the pages tab

**Comment by adamdriscoll** [comment]
Because of the files view that was added to recent versions, I don't think we need to overcomplicate the Files (now module) tab. You can create separate files if you want individual places for each function. I'll likely implement some editor improvements for better navigation between functions defined in a single function, similar to VS Code.
