### ISSUE TITLE
5.0.5 - New-PSUVariable -Credential not working

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#3689]
### Version

5.0.4

### Severity

Medium

### Environment

msi

### Steps to Reproduce

```
# Createting a Secret String Variable - Works!
New-PSUVariable -Integrated -ComputerName "localhost" -Name "TestSecret994" -Description "Test Description 994" -Vault Database -Value "hello" -TrustCertificate
```

```
# Creating a Credentials Variable - Doesn't work!
$Password = "password" | ConvertTo-SecureString -AsPlainText -Force
$PSCredential = [PSCredential]::new("user", $Password)
New-PSUVariable -Integrated -ComputerName "localhost" -Name "TestCreds999" -Description "Test Creds 999" -Vault Database -Credential $PSCredential -TrustCertificate
```

Error Toast shown:
![image](https://github.com/user-attachments/assets/38b29b78-bf6b-4660-9935-c85508429168)

Also tried using the "new" -AppToken method... Didn't have success at all. Either with Secure strings nor Creds... The only way so far that works partially (only with strings atm) is using the -Integrated switch.

What am I doing wrong?

Thanks for your help!!!

### Expected behavior

```console
PSCredential Objects should work with New-PSUVariable
```

### Actual behavior

```console
PSCredential Objects do not work with New-PSUVariable
```

### Additional Environment data

5.0.5

**Comment by adamdriscoll** [comment]
@donlent - The -Integrated switch actually has no effect. It's just there so people's scripts continue to work without changes. 

We've added a permissive security model to the module that should solve the permission issue with the cmdlets: https://docs.powershelluniversal.com/config/module#authorization-security-model

The -Credential parameter is actually a credential for authenticating against PSU and not for creating credentials. Pass the credential to -Value instead. You're getting a 401 because it's trying to use the credential you created as the authentication for the cmdlet. 

I just checked and we actually have a test in place to verify that New-PSUVariable creates secrets properly, so it looks like this is working from my end.

**Comment by donlent** [comment]
Hey @adamdriscoll 
First of all thanks a lot! As always super fast which helps a lot in case of project development issues like this one!

OK understand. I took the example above from another issue where you explained that it has to be done that way:
https://github.com/ironmansoftware/powershell-universal/issues/712#issuecomment-972962038

Anyway, now it worked! Thanks a lot! Also for having explained the auth security model which is new in PSU 5.
Strange that it's not working though.. I created an AppToken with "Administrator" rights so don't know why it doesn't work... 
But it's ok for now it's working with the "Permissive" Model. So I'm OK. :-)

Thanks again!
