### ISSUE TITLE
Error rendering dashboard after upgrade to 4.4.0

### ISSUE THREAD

**Issue by ganslm** [ironmansoftware/powershell-universal#3705]
### Version

4.3.4

### Severity

Critical

### Environment

msi

### Steps to Reproduce

Upgrade from 4.3.4 to 4.4.0 and start a dashboard.

### Expected behavior

```console
Start Dashboard.
```

### Actual behavior

```console
Error rendering dashboard (see txt file)
```

### Additional Environment data

Version Number: 4.4.0
Operating System: Windows Server 2022
SQL: Microsoft SQL Server 2022

### Screenshots/Animations

[Error rendering dashboard.txt](https://github.com/user-attachments/files/16885472/Error.rendering.dashboard.txt)

**Comment by adamdriscoll** [comment]
I'm unable to reproduce this in my lab. I installed v4.4.0 fresh using the MSI. I tried both with a simple dashboard and our docs dashboard and they both render. Are you hosting with Kestrel\MSI or IIS?

**Comment by ganslm** [comment]
I´m hosting with regular MSI on Windows Server 2022 and upgraded from v4.3.4.

**Comment by rwidmark** [comment]
Was the same for me, reverted back to 4.3.4 solved it.
Same setup as @ganslm but with the SQLLite

**Comment by adamdriscoll** [comment]
I'm sure you've tried all these things but have you: 

- Uninstalled v4.3.4 and then install v4.4.0 rather than just upgrade
- Clear browser cache\use different browser 

If possible, try a nightly build: 

https://powershelluniversal.com/release/powershell-universal-nightly

Just trying to narrow down what could cause this. I don't think it would matter what server-side configuration, aside from the app itself.

**Comment by ganslm** [comment]
A clean Installation (uninstall v4.3.4 and then install v4.4.0), as you mentioned worked for me.

Thank you.

**Comment by rwidmark** [comment]
Can confirm that the following did work for me.
Uninstall old version deleted the folder that did contain the DB and repository in programdata.
Rebooted
Installed new version

But the login page don't seem to take the settings from loginpage.ps1

@adamdriscoll
