### ISSUE TITLE
5.0.9 - Schedules.ps1 being updated due to swapping parameter positions every few minutes

### ISSUE THREAD

**Issue by bt-ndollimount** [ironmansoftware/powershell-universal#3847]
### Version

5.0.9

### Severity

Low

### Environment

msi

### Steps to Reproduce

It appears that every 2-3 minutes, PSU is updating the Schedules.ps1 file but it's swapping the order of some parameters back and forth. This is causing a new GIT entry every 2-3 minutes.

### Expected behavior

```console
The parameters shouldn't be swapping places.
```

### Actual behavior

```console
The parameters are swapping places so the Schedules.ps1 file is legitimately being updated every 2-3 minutes.
```

### Additional Environment data

You can see in between taking the screenshots, there was another update to sync down.

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/f541fedf-55f0-4e1e-bd73-f766aff0dbfc)
![image](https://github.com/user-attachments/assets/8dd583cd-d9a7-4726-b54e-0080f5ea0a00)

**Comment by adamdriscoll** [comment]
Do you have something automated that is creating\removing schedules? Even onetime schedules? Just trying to think why it would try to write this file every few minutes. 

That said, it shouldn't be doing the whole switcheroo. 

Edit: Either way, this is an easy fix to just ensure that parameters are alphabetic order to avoid it ever doing this.

**Comment by bt-ndollimount** [comment]
@adamdriscoll So our Git ended up crapping out on the servers and they all stopped syncing. After getting things sorted this morning (clearing everything, re-cloning, etc.), I'm not seeing that a new schedule is being removed/added back and forth, not parameters this time. So it appears that it's two servers fighting with each other, writing "their" set of schedules over and over.

**Comment by bt-ndollimount** [comment]
> @adamdriscoll So our Git ended up crapping out on the servers and they all stopped syncing. After getting things sorted this morning (clearing everything, re-cloning, etc.), I'm not seeing that a new schedule is being removed/added back and forth, not parameters this time. So it appears that it's two servers fighting with each other, writing "their" set of schedules over and over.

So I believe I have this sorted. First, I paused the Git sync. Then going to two of the three hosts, I opened the repository in VSCode, which showed that there were staged changes to the schedules.ps1 file (to remove the schedule I had recently created). I discarded the changes on both hosts then restarted the PSU service. Once they came back up, I logged into both individually to confirm the new schedule was there. I resumed the Git sync and things appear to be settled down and working as expected.

I guess this poses the question of how this came to be. It's obviously due to the multi-node configuration. I don't know how PSU works under the hood, specifically when creating/making changes to schedules. Does it immediately reach out to each other node to update them in real time or is it supposed to reload when it detects a file change (from a Git Sync)? If the latter, there seems to be something not working as expected otherwise this shouldn't have happened. It should have reloaded the updated schedules.ps1 file upon sync rather than thinking it should save its current in-memory schedule over the schedules.ps1 instead; this is what seems like was happening where each node thought its current schedule config was the truth and kept writing it to the schedules.ps1 file instead of reloading the changes when the file was updated via Git sync. One would save its settings, git sync occurs, the other would see the difference and overwrite the file, git sync occurs, and back and forth.

**Comment by adamdriscoll** [comment]
The git sync shouldn't be saving any files during the process. This is how it works in automatic mode: 

Service starts and runs a git sync 
- git pull
- if unstaged changes
    - git add . 
    - git push
- synchronize with internal database 
- schedule git sync to run on interval 

When interval is hit: 
- git pull
- if unstaged changes
    - git add . 
    - git push
- synchronize with internal database 

What I'm wondering is if some process in between was touching the schedule and it was causing the schedules to update so on the next git sync, it would push changes. It may not even have been changing anything per se, but just rewriting the schedules.ps1 file down using its own index. This happened on both servers so it would ping pong back and forth between the two and eventually just got into a bad state because of conflicts or whatnot. I think one-time schedules might cause this because they don't end up in the schedules.ps1 but may still cause the file to be written. 

I think the overall problem is that PSU is not maintaining an order to resources in the configuration files. It's arbitrary and mostly just based on internal IDs to each server. This could cause the extract scenario you are seeing. 

We need to make the order deterministic. This would likely be alphabetic by resource name or another identifier that is the same between both servers. I'm a bit surprised this has never happened to anyone else since it's always worked like this but you've definitely identified an issue in the configuration system. 

All that to say, I'll open another issue for this to ensure we get it resolved.

**Comment by bt-ndollimount** [comment]
@adamdriscoll Just as an update, it's back to two servers writing the parameters in different order, ping ponging Git updates back and forth. You mentioned above it was an easy fix to write the parameters in alphabetical order; was that change actually made? I'd very much be willing to install a nightly build that had that fixed 🙂

EDIT
I see the nighty build has that fixed in it. Looks like I'm upgrading!
