### ISSUE TITLE
5.0.10 - Send-PSUEvent partially "broken" since 5.0.9 changes

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#3908]
### Version

5.0.10

### Severity

Critical

### Environment

msi

### Steps to Reproduce

Dear @adamdriscoll 

Really sorry to bother again with new stuff but unfortunately since your changes documented here the Send-PSUEvent doesn't work anymore **when used inside of modules** :-(
https://github.com/ironmansoftware/powershell-universal/issues/3810

This again breaks again some project functionality unfortunately. in 5.0.6 it used to work without problem and now I get this error message:

![image](https://github.com/user-attachments/assets/b2289043-a807-49dd-a2a5-f763825b3f7c)

I tried adding -ComputerName, -AppToken, -TrustCertificate, -Integrated... various combinations but no success!
Then I thought to rollback to a previous version before your changes (5.0.8) but unfortunately the DB schema seems to not "like" it and therefore I'm really stuck now. :-(
Really hope that you find the source of the problem!

Additional Info:
The appsettings.json contains this:
```
"Api": {
      "SecurityModel": "Permissive",
	  "TrustCertificate": true
  }
```

Unfortunately it doesn't help so don't know what it is.

Thanks a lot for your much appreciated help!!

### Expected behavior

```console
Send-PSUEvent should work as it used to work on 5.0.6
```

### Actual behavior

```console
Send-PSUEvent doesn't work anymore as it used to work from inside Modules and I wasn't able to find a workaround to get it to work.
```

**Comment by adamdriscoll** [comment]
I'm trying to reproduce this but haven't yet. The problem is that the cmdlet can't find the proper URL to call. It effectively null. This URL can be set in a couple of different ways: 

## Automatically by PSU 

It guesses the URL based on the node name and configured port. This can fail when using behind a proxy like IIS or Azure App Services

## Manually via AppSettings.json

```
"Api": {
      "SecurityModel": "Permissive",
	  "TrustCertificate": true,
     "Url": "https://mycustomurl.com"
  }
```

In these configurations, PSU should be setting $PSUComputerName and $PSU_INTEGRATED_API_URL to the value of the PSU server URL. In your module, you can check this. Use Write-Host to output the values. 

```
function Send-Stuff {
    Write-Host $PSU_INTEGRATED_API_URL
    Send-PSUEvent -Hub 'Hub' -Data @{
        "Nice" = "Cool"
    } -Verbose
}
```

The value will appear in the applog. 

![image](https://github.com/user-attachments/assets/4b549654-7d20-4411-845e-aa3edcfd6800)

## Manually via -ComputerName 

Make sure to specify the full URL if you are hosting on a port other than 5000. For example: 

```
Send-PSUEvent -Hub 'Hub' -ComputerName https://mycustomurl:443
```

It does look like there is an issue where if you set computerName but no app token, it will stomp on the value and use $PSU_INTEGRATED_API_URL. 

You could try to work around this like: 

```
$PSU_INTEGRATED_API_URL = "https://mycustomurl:443"
Send-PSUEvent -Hub 'Hub' -ComputerName $PSU_INTEGRATED_API_URL
```

**Comment by donlent** [comment]
Hey @adamdriscoll 
Don't even have words to express my gratitude! THANKS A LOT! 🙏
Indeed this is surely the right route to the source of the problem!
I was able to workaround the issue by specifying the `-ComputerName` and putting the right URL (so, not just the real computername) however it wasn't enough! It also wanted to have the `-AppToken` specified.

As said, it works now again as it used to work with 5.0.6 however I wanted to let you know the current situation, since I'm not sure if you need to tweak a little bit here and there to make it more transparent maybe...?

Additional info for you, I also tried to specify the Api URL in the AppSettings as you mentioned in your post however it seems that it doesn't work. Also the "Permissive" setting maybe is not really "permissive" right now. I understood that when set like that you don't need to use any AppTokens. In reality we do need them as you can see...

As said, just sharing my thoughts and experiences with you in case there are still some hidden issues spread somewhere in your main code.

Take care and thanks again,
Don

**Comment by adamdriscoll** [comment]
Thanks for the feedback @donlent. There is something amiss here because it seems to be not receiving the automatic variables that should make this "all work" without any of this configuration. I'll leave this issue open and see if we can get to the bottom of it for the next release.

**Comment by adamdriscoll** [comment]
Hey @donlent,

I haven't been able to reproduce this myself. I'm wondering if you could add this function to your module. 

```
function New-UDVariableTable {
    $Data = Get-Variable | ForEach-Object {
        [PSCustomObject]@{
            Name = $_.Name 
            Value = if ($_.Value) { $_.Value.ToString() }
        }
    }

    New-UDTable -Data $Data
}
```

In an app, you would then call that function. 

```
New-UDApp -Content { 
    New-UDVariableTable
 }
```

The idea is that I'm trying to understand what variables are set in the current module scope. In my environment, I see the PSU_INTEGRATED_API_URL variable as well as the SecurityContext. This values should always be set.

**Comment by donlent** [comment]
Dear @adamdriscoll 
Thanks a lot for taking care of this. And sorry if I couldn't get back to you already last week.
I'll try my best to replicate the issue using your provided code by latest mid of this week. Unfortunately because of other projects I probably won't have time before Wednesday...
Thanks for your patience and efforts (as always ;-) )
Best regards,
Don

**Comment by donlent** [comment]
Dear @adamdriscoll 
So finally I was able to dedicate some time to this. Thanks again for your patience on this.

So here is the result:

The **PSU_INTEGRATED_API_URL** is set to (generalized for privacy reasons) **"https://my.url.com"**
The **SecurityContext** is set to **"PowerShellUniversal.SecurityContext"**

Does this help for now or is there anything else I can do?
Obviously if you'd like to have a quick remote session we could arrange that too.

Best regards,
Don

**Comment by adamdriscoll** [comment]
Strange. That looks like it should be working. I just added a whole bunch of new Write-Verbose calls to the cmdlets to get a better handle on what is happening in your environment. That change will be in 5.0.14. We'll want to collect that once released. If we still are unsure what's happening, let's setup a call.

**Comment by adamdriscoll** [comment]
I reimplemented -Integrated in v5.0.15. This effectively reverts the behavior back to v4 stay of API calls. If you include -Integrated in your Send-PSUEvent call, it will use the backchannel rather than the external gRPC web service. It will avoid any cert issues or cred issues. Permissive mode is required to use this switch. 

I'm also considering making a global setting to allow for this everywhere.

**Comment by donlent** [comment]
Thank you @adamdriscoll 
I will test that once released and let you know.
Best regards,
Don
