### ISSUE TITLE
Secrets randomly go poof

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3959]
### Version

5.0.13

### Severity

Critical

### Environment

Nested IIS

### Steps to Reproduce

use the application
recycle app pools
edit git hub settings

### Expected behavior

```console
secrets should stay in the database
```

### Actual behavior

```console
randomly get deleted
```

### Additional Environment data

IIS is setup on a SQL backend with 2 web servers

i know that the rows were deleted because the ids go poof and start up again on record 7

The Variable table and the VariableValues table both suffer from getting their rows deleted, randomly.

**Comment by adamdriscoll** [comment]
Haven't been able to reproduce this. I did make some changes to prevent weird reconfiguration issues and it may have resolved it but that's unclear at the moment. Moving into next milestone until I have a good way to reproduce this.

**Comment by adamdriscoll** [comment]
I found an edge case that could cause this. Hoping that it's the reason for why you are seeing it.

**Comment by JessePeden** [comment]
> I found an edge case that could cause this. Hoping that it's the reason for why you are seeing it.

Can you provide any details about this edge case?  Just curious.

**Comment by adamdriscoll** [comment]
The configuration class for variables has some logic to delete secrets when a variable is deleted. If you delete the variable from the UI and it's in the database vault, it will delete the secret from the database. When reconfiguring based on file system or git change, shouldn't be deleting the secret variable since source node should have already done this. 

The problem was a race condition that would cause the git sync and the file system watcher to effectively delete and add variables . It wouldn't be visible to the end user except the configuration system was also deleting the secret values from the database. 

So there were effectively 2 issues fix: 

- Prevent the race conditon
- Prevent the variable configuration class from deleting secrets when a change comes from the file system

**Comment by JessePeden** [comment]
Ahh. Nice find. That makes sense and explains why it was seemingly random with who it would affect and who it wouldn't.
