### ISSUE TITLE
PSU 5.0.14 - Variables window is blank (including any buttons to create variables)

### ISSUE THREAD

**Issue by JessePeden** [ironmansoftware/powershell-universal#4002]
### Description of Issue

The Variables page is entirely blank after upgrading to 5.0.14, including the buttons to create variables.  Restarting the host made no difference.  I can still access the variables via API (such as through VS Code) or directly on the host by opening variables.ps1, but this won't help with Secret variables since they aren't stored in the config.

### Version

5.0.14

### Severity

Critical

### Hosting Method

MSI (Windows Service)

### Operating System

Windows

### Database

SQLite

### Licensed

Yes

### Features

Variables

### Screenshots/Animations

![2024-10-31_14-38-45](https://github.com/user-attachments/assets/11e01341-8bdf-4ac2-b54a-4fe122731a6f)

**Comment by JessePeden** [comment]
Through some testing, I’ve found that if I comment out the entire variables.ps1 file, I can get the page to display again. So, something I have a variable for doesn’t seem to be liked in 5.0.14 that wasn’t a problem in any of the past versions.

**Comment by JessePeden** [comment]
There are some more details on the forum [post](https://forums.ironmansoftware.com/t/variables-page-is-entirely-blank-post-psu-5-0-14-upgrade/) about this, after I did more testing.

**Comment by adamdriscoll** [comment]
As mentioned on the forum post, it looks like it has to do with tags.

**Comment by JessePeden** [comment]
It's closed, as in you already found why tags is breaking things?

For the record, I don't have tags on any of my variables, so I don't understand how tags are breaking things in my environment when they're not even in use.  The only tags I have are on scripts.

**Comment by adamdriscoll** [comment]
I closed it because I could reproduce and saw that a component that is supposed to be displaying tags for variables is throwing this error. I added error handling to prevent that. The component tags the variable and looks up the tags so it can get the right color for the tag and then displays them. 

The list of tags on the variable were null rather than an empty array, which the component expected. It's not checking for both null and empty when displaying tags.
