### ISSUE TITLE
API Endpoint, leading zero removed from query/param.

### ISSUE THREAD

**Issue by dclarkSSOE** [ironmansoftware/powershell-universal#4095]
### Description of Issue

Just getting started with APIs and looking to utilize them a bit more for some of our remote processes.  Our samaccountname's are a 5 digit number, and while most of them do not start with a leading zero, some do.  If I pass a samaccountname via either /test/:userid or just /test?userid= as an endpoint, the leading zero is always removed.

I'm hoping this is just a me issue, but I searched the closed tickets and swagger ui info for a solution before posting.

### Version

5.0.16

### Severity

Low

### Hosting Method

MSI (Windows Service)

### Operating System

Windows

### Database

SQL

### Licensed

Yes

### Additional Environment data

Windows Server 2022 Core

**Comment by adamdriscoll** [comment]
@dclarkSSOE - I'm trying to reproduce this but can't at the moment. Here are my tests: 

```
param($UserId)

$UserId
```

Result:

```
PS C:\Users\adamr> Invoke-RestMethod -Uri 'http://localhost:5000/api/group?userId=01234' -Method 'GET'
668
```

I think the problem is that the result is being translated somehow by Invoke-RestMethod and causing an invalid value. That said, I'm seeing the value is correct in the endpoint. 

If I use Invoke-WebRequet, the content is correct.

```
PS C:\Users\adamr> Invoke-WebRequest -Uri 'http://localhost:5000/api/group?userId=01234' -Method 'GET'

StatusCode        : 200
StatusDescription : OK
Content           : 01234
```

If I return a hashtable, Invoke-RestMethod returns the proper value. 

```
param($UserId)

@{
    UserId = $UserId
}
```

PS C:\Users\adamr> Invoke-RestMethod -Uri 'http://localhost:5000/api/group?userId=01234' -Method 'GET'

```
UserId
------
01234
```

**Comment by MikeShepard** [comment]
FWIW, 01234 in octal (base-8) is 668 in decimal.

**Comment by dclarkSSOE** [comment]
@adamdriscoll 

I can confirm the same behavior you mentioned.  Invoke-RestMethod returns "1234" in your instance above, whereas Invoke-WebRequest returns "01234".  Returning a hashtable, both methods work to return "01234".

Low on time today but will provide more tests/updates later.  Appreciate you looking into it.

**Comment by adamdriscoll** [comment]
It looks like you have to convert it to JSON if you want it ensure that the value is properly converted in Invoke-RestMethod. The issue is that if you return a string as-is from an endpoint, it just returns that string. It doesn't run it through ConvertTo-Json since it assumes it's already in the expected format. This means, it returns the literal `012345`. You'll see that ConvertFrom-Json will drop the 0 on the front. This is the same serializer code used in Invoke-RestMethod. 

```
PS C:\src\universal\src> 012345 | ConvertFrom-Json
12345
```

Instead, if you run it through ConvertTo-Json, it will put quotes around the string. The result will be `"012345"`.

```
param($MyId)

$MyId | ConvertTo-Json
```

The result is that Invoke-RestMethod and ConvertFrom-Json correctly convert the value to the proper string. 

```
PS C:\src\universal\src> Invoke-RestMethod -Uri 'http://localhost:5000/api/01234' -Headers @{} -Method 'GET'
01234
PS C:\src\universal\src> Invoke-WebRequest -Uri 'http://localhost:5000/api/01234' -Headers @{} -Method 'GET'

StatusCode        : 200
StatusDescription : OK
Content           : "01234"
RawContent        : HTTP/1.1 200 OK
```
