### ISSUE TITLE
Session Timeout Hook 

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#57]
#### Description

https://forums.universaldashboard.io/t/universal-1-2-8-testing/3131/8?u=adam

Probably add something to New-UDDashboard like -OnSessionTimeout to execute a scriptblock when a user is logged out.

**Comment by donlent** [comment]
That would be briliant Adam and something I was looking for since the beginning!

Maybe you remember this issue here which I opened a while ago:
https://github.com/ironmansoftware/issues/issues/700

I think if you would add to this feature also the possibility to trigger a logoff directly instead of having to call:
```
Invoke-UDRedirect '/api/v1/signout' -OpenInNewWindow
Invoke-UDJavaScript 'window.location.reload()'
```
That would resolve this issue as well and you could close my issue with that one ;-)

Example:
```
New-UDDashboard like -OnSessionTimeout {
Invoke-PSULogoff
}
```

**Comment by adamdriscoll** [comment]
We're adding this as a trigger.
