### ISSUE TITLE
New-UDButton Icon not working

### ISSUE THREAD

**Issue by t3chyphil** [ironmansoftware/powershell-universal#659]
### Steps to Reproduce

Hey Adam and team,

This is a issue I'm opening up in relation to my forum query https://forums.ironmansoftware.com/t/upgrade-path-from-2-4-0-to-2-9-0/5899 regarding buttons.

The [button doc example](https://docs.universaldashboard.io/components/button) states we can use **New-UDButton -Icon Plus** but Dashboard had a red toast pop up saying...

'Cannot bind argument to parameter 'Icon', because PSTyleNames of the argument do not match the PSTypeName required by the parameter: UniversalDashboard.Icon.'

I simply installed the MSI Windows installer on my server. Should I be installing other modules to make these cmdlets available? When I do a Get-Command *New-UDButton* on the server it's installed on, it returns nothing, yet it's rendering a button on the dashboard. Arg I'm so confused!

If I **Install-module UniversalDashboard** then run  Get-Command *New-UDButton*, it returns an output. 

Thank you

### Expected behavior

```console
See text.
```

### Actual behavior

```console
See text.
```

### Environment data

Windows Server 2019 Standard 1809
Windows Powershell 5.1

**Comment by adamdriscoll** [comment]
@t3chyphil I see the issue here. You're mixing the old v2 documentation with the new v3 framework. 

If you want to use v2, you need to specify the v2 framework for your dashboard. 

![image](https://user-images.githubusercontent.com/1256531/140560875-734c27dc-8709-4ded-a146-7e66af69575d.png)

Then the documentation you are using will work. 

If you want to use the v3 framework, you will need to use the new syntax. 

https://docs.powershelluniversal.com/userinterfaces/dashboards/components/inputs/button#buttons-with-icons-and-label

**Comment by t3chyphil** [comment]
Thank you Adam. I didn't realise the Dashboards used a framework different to the overall version number of the product. 

Thanks for your help.
