### ISSUE TITLE
Auto-deploy should only reload a single dashboard

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#75]
**Is your feature request related to a problem? Please describe.**

When auto-deploy is enabled, all dashboards with auto-deploy will restart if a change is made anywhere in PSU. 

**Describe the solution you'd like**

Only the dashboard where the change is made should restart. Dashboards should be stored in folders to avoid this issue. 

**Describe alternatives you've considered**

Turn off auto-deploy for production use.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/dashboard-autodeploy-feature-ignore-settings/6484/2

**Comment by rbleattler** [comment]
To clarify the scenario I was in when I created the post, my repository is *currently* structured similar to what is shown below. The 'PrimaryDashboard' dashboard includes functionality that generates files which are placed in the **PrimaryDashboard/Downloads** directory, so that the files may be served from the same dashboard for download using a button. If the **Auto Deploy** functionality is enabled, once a file is dropped into the directory, it automatically reloads the dashboard. 

Initially this dashboard generated an empty file on load, but that resulted in an endless reload loop because of this functionality. 


📦PowershellUniversal
 ┣ 📂.git 
 ┃ ┗ ...
 ┣ 📂.universal
 ┃ ┣ 📜authentication.ps1
 ┃ ┣ 📜dashboards.ps1
 ┃ ┣ 📜endpoints.ps1
 ┃ ┣ 📜environments.ps1
 ┃ ┣ 📜licenses.ps1
 ┃ ┣ 📜loginpage.ps1
 ┃ ┣ 📜publishedFolders.ps1
 ┃ ┣ 📜roles.ps1
 ┃ ┣ 📜schedules.ps1
 ┃ ┣ 📜scripts.ps1
 ┃ ┣ 📜settings.ps1
 ┃ ┣ 📜triggers.ps1
 ┃ ┗ 📜variables.ps1
 ┣ 📂dashboards
 ┃ ┣ 📂SharedAssets
 ┃ ┃ ┗ 📜custom.css
 ┃ ┣ 📂Testing
 ┃ ┃ ┗ 📜Testing.ps1
 ┃ ┗ 📂PrimaryDashboard
 ┃&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;┣ 📂Downloads
 ┃&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;┗ 📜PrimaryDashboard.ps1
 ┣ 📂ExternalScripts
 ┃ ┣ 📂Functions
 ┃ ┃ ┣ 📜ScriptFunctions.ps1
 ┃ ┃ ┗ ...
 ┃ ┣ 📜Script1.ps1
 ┃ ┗ ...
 ┣ 📂Dependencies
 ┃ ┣📂DependencyModule
 ┃ ┗ ...
 ┣ 📂Resources
 ┃ ┣ 📂AdditionalStuff
 ┃ ┃ ┗ ...
 ┃ ┗ 📂Etc
 ┣ 📜.gitignore
 ┗ 📜Local.db
