### ISSUE TITLE
Invoking IntelliSense requires mouse input

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#803]
IntelliSense should not require mouse input. You should be able to use the keyboard. 

VS 2021.12.2

https://forums.ironmansoftware.com/t/powershell-interactive-window-not-working-as-expected/6349

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/powershell-interactive-window-not-working-as-expected/6349/3

**Comment by KyleKolander** [comment]
![Intellisense Mouse Click](https://user-images.githubusercontent.com/22461822/147301912-25ab3f8d-f9c1-4614-83d6-7881cc81a859.gif)

**Comment by KyleKolander** [comment]
As you can see in the gif, in order to select exactly what has already been typed (and make the intellisense dropdown go away), it requires a mouse click.  Hitting ESCAPE makes the typed command go away entirely.  Hitting TAB or ENTER selects the automatically highlighted entry in the intellisense dropdown and adds it to the typed command.
