### ISSUE TITLE
PSU, get hostname from visitor?

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#842]
I have been looking and as far as I can tell it's not possible to get the hostname from the visitor. IP address is.

Is it something that's possible?
It would bee great in so many ways :)

**Comment by adamdriscoll** [comment]
It's not reliable. If you are on a local intranet and can use DNS to look up the client IP, then you could resolve the IP to a host name. You could use Resolve-DnsName for this. 

It's possible the client could send the host name but is not sound since it could be adjusted easily in the headers (or however it's sent). 

https://stackoverflow.com/questions/50742479/how-to-get-a-clients-computer-name-in-asp-net-core

**Comment by adamdriscoll** [comment]
I'm going to close this since it's not something we'll likely implement in PSU.
