### ISSUE TITLE
Verbose output cannot be output from APIs

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#944]
### Steps to Reproduce

Using redirection, you cannot output to a file for verbose output. 

Add-ADGroupMember -Verbose *>> Output.txt

### Expected behavior

```console
Verbose output can be redirected for logging purposes.
```

### Actual behavior

```console
Verbose output is blank.
```

### Environment data

2.7.4

**Comment by adamdriscoll** [comment]
This seems to work for me. 

![image](https://user-images.githubusercontent.com/1256531/153311314-06d63d72-4adc-4513-b792-1e26eadf8ebf.png)

**Comment by El-Heffe** [comment]
Please try:
New-PSUEndpoint -Url "/test" -Endpoint {
#Debug flags
$DebugOutput = "C:\ProgramData\PowerShellUniversal\debug.txt"
"This is the line before" *>> $DebugOutput
Add-ADGroupMember -Verbose -Identity  “test-group" -Members "test-user"  -Confirm:$false *>> $DebugOutput
"This is the line after" *>> $DebugOutput
New-PSUApiResponse -Body "Complete" -StatusCode "200"
} -ErrorAction "Stop"

Observed behavior: (log from debug.txt)
This is the line before
This is the line after

Expected Behavior:
This is the line before
VERBOSE: Performing the operation "Set" on target "CN=test-group,OU=test-ou,DC=ACME,DC=COM".
This is the line after

**Comment by adamdriscoll** [comment]
@El-Heffe This actually worked for me as well. 

![image](https://user-images.githubusercontent.com/1256531/153495375-59a3b01f-aa48-45ba-af7c-77054bea089c.png)

What I do notice that is if there is an error with Add-UDGroupMember, it's not sent to the log. That said, I will see the error returned by the rest call. 

![image](https://user-images.githubusercontent.com/1256531/153495828-75261c77-298d-4f08-bdd2-f0d06a5da538.png)
